import { showToast } from '@poluru-labs/enterprise-design-system-wc';

const icon = (name) => `<i class="bi bi-${name}" aria-hidden="true"></i>`;
const escape = (v) => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav = [['overview','grid-1x2','Overview'],['campaigns','megaphone','Campaigns'],['audiences','people','Audiences'],['calendar','calendar3','Content calendar'],['budgets','wallet2','Budgets'],['channels','bar-chart','Channel performance']];
const initial = [
 {name:'Fall into something new',desc:'Fall collection · Brand awareness',channel:'Multi-channel',icon:'layers',owner:'Anika Poluru',status:'Active',budget:24000,spent:16480,reach:'284.6K',rate:'4.82%',color:'peach'},
 {name:'The next chapter',desc:'Product launch · Acquisition',channel:'Paid social',icon:'instagram',owner:'Rohan Poluru',status:'Active',budget:18000,spent:12600,reach:'192.4K',rate:'3.94%',color:'lavender'},
 {name:'Made for your everyday',desc:'Always-on · Engagement',channel:'Email',icon:'envelope',owner:'Maya Poluru',status:'Active',budget:8500,spent:5100,reach:'86.2K',rate:'6.21%',color:'mint'},
 {name:'A little more Meridian',desc:'Loyalty program · Retention',channel:'Organic social',icon:'chat-square-heart',owner:'Arjun Poluru',status:'Scheduled',budget:12000,spent:0,reach:'—',rate:'—',color:'blue'},
 {name:'Meet your new favorites',desc:'Holiday preview · Acquisition',channel:'Paid search',icon:'search',owner:'Nisha Poluru',status:'Draft',budget:15000,spent:0,reach:'—',rate:'—',color:'sand'},
];
const money = n => '$' + n.toLocaleString('en-US');
const badge = s => `<eds-badge variant="${s==='Active'||s==='Published'?'success':s==='Scheduled'?'info':'neutral'}" pill>${s}</eds-badge>`;
const channels = [['instagram','Paid social','42.8K','4.2x',42,'#738aaa'],['search','Paid search','31.6K','5.1x',31,'#1a2a4f'],['envelope','Email','18.2K','6.8x',18,'#77b7a7'],['globe2','Organic','8.4K','3.6x',9,'#c6b392']];
const events = [['18','FRI','The fall edit is here','Email newsletter','09:00 AM','envelope','Maya Poluru'],['19','SAT','Behind the collection','Instagram · Carousel','11:30 AM','instagram','Anika Poluru'],['20','SUN','Your everyday, elevated','Blog · Editorial','10:00 AM','file-earmark-text','Rohan Poluru']];

export class MeridianShell extends HTMLElement {
 connectedCallback(){
  this.campaigns=structuredClone(initial); this.status='All campaigns'; this.query=''; this.metric='Revenue'; this.period='This month';
  this.render(); this.onRoute=()=>this.renderPage(); window.addEventListener('hashchange',this.onRoute); this.renderPage();
  this.addEventListener('click',e=>this.handleClick(e));
  this.addEventListener('eds-change',e=>{if(e.target.id==='select-all'||e.target.classList.contains('row-check')){const checks=[...this.querySelectorAll('.row-check')];if(e.target.id==='select-all')checks.forEach(c=>c.checked=e.detail.checked);const count=checks.filter(c=>c.checked).length;const all=this.querySelector('#select-all');all.checked=count===checks.length&&count>0;all.indeterminate=count>0&&count<checks.length;this.querySelector('#selection-count').textContent=count?`${count} campaigns selected`:`Showing ${checks.length} of ${this.campaigns.length} campaigns`;}});
  this.addEventListener('eds-click',e=>this.handleAction(e.target.dataset.action,e.target));
  this.querySelector('#campaign-search').addEventListener('eds-input',e=>{this.query=e.detail.value || ''; if(this.route!=='campaigns')location.hash='#/campaigns';else this.renderPage();});
  this.querySelector('#period').options=[{label:'This month',value:'This month'},{label:'Last month',value:'Last month'}];
  this.querySelector('#period').value=this.period;
  this.querySelector('#period').addEventListener('eds-change',e=>{this.period=e.detail.value;this.renderPage();});
  this.querySelector('#new-channel').options=['Multi-channel','Paid social','Paid search','Email','Organic social'].map(value=>({value,label:value}));
  this.querySelector('#new-owner').options=['Anika Poluru','Rohan Poluru','Maya Poluru','Arjun Poluru','Nisha Poluru'].map(value=>({value,label:value}));
  this.querySelector('#new-channel').value='Multi-channel';this.querySelector('#new-owner').value='Anika Poluru';
  this.keyHandler=e=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();this.querySelector('#campaign-search').shadowRoot?.querySelector('input')?.focus();}if(e.key==='Escape')this.toggleSidebar(false);}; document.addEventListener('keydown',this.keyHandler);
 }
 disconnectedCallback(){window.removeEventListener('hashchange',this.onRoute);document.removeEventListener('keydown',this.keyHandler);}
 render(){this.innerHTML=`
 <header class="topbar"><div class="brand-group"><eds-tooltip content="Toggle sidebar"><eds-button variant="tertiary" icon="menu" icon-only accessible-label="Toggle sidebar" data-action="sidebar" id="sidebar-toggle" aria-expanded="false"></eds-button></eds-tooltip><a class="brand" href="#/overview"><span class="brand-mark">m<span>•</span></span><span>meridian<span class="brand-dot">.</span></span></a><span class="brand-divider"></span><span class="workspace-name">Marketing workspace</span></div><div class="top-actions"><eds-search id="campaign-search" placeholder="Search campaigns..." size="sm"></eds-search><eds-kbd keys="⌘K"></eds-kbd><span class="brand-divider"></span><eds-tooltip content="Notifications"><eds-button variant="tertiary" icon="bell" icon-only accessible-label="Notifications" data-action="notifications"></eds-button></eds-tooltip><button class="profile" data-action="profile" aria-label="Profile for Anika Poluru"><eds-avatar name="Anika Poluru" size="sm"></eds-avatar></button></div></header>
 <aside class="sidebar" inert><div class="nav-caption">WORKSPACE</div>${nav.map(([id,i,label])=>`<a href="#/${id}">${icon(i)}<span>${label}</span>${id==='campaigns'?'<span class="nav-count">5</span>':''}</a>`).join('')}<div class="sidebar-bottom"><div class="workspace-avatar">M</div><div><strong>Meridian Studio</strong><small>Marketing team</small></div></div></aside>
 <div class="workspace"><main id="view"><div class="page-heading"><div><div class="eyebrow">YOUR MARKETING, IN FOCUS</div><h1 id="page-title">Overview</h1><p id="page-description">A clear view of what’s working. And what’s next.</p></div><div class="heading-actions"><span class="date-control">${icon('calendar4')}<eds-select id="period" size="sm"></eds-select></span><eds-button variant="secondary" data-action="export" icon="download">Export report</eds-button><eds-button data-action="new" icon="plus">Create campaign</eds-button></div></div>
 <nav class="section-nav" aria-label="Marketing sections">${nav.map(([id,i,label])=>`<a href="#/${id}" data-route="${id}">${icon(i)}${label}</a>`).join('')}<span class="sync-status"><span></span> Updated just now</span></nav><div id="page-content"></div><footer><span><span class="footer-mark">m.</span> A little clarity. A lot of possibility.</span><span>Meridian Marketing <span class="footer-dot">•</span> Sample workspace · September 2026</span></footer></main></div>
 <eds-modal id="create-modal" heading="Create a campaign" close-on-backdrop close-on-escape><p class="muted">Give your next great idea a place to grow.</p><div class="form-stack"><eds-input id="new-name" label="Campaign name" placeholder="e.g. A season of new possibilities" required></eds-input><div class="form-grid"><eds-select id="new-channel" label="Channel"></eds-select><eds-select id="new-owner" label="Campaign owner"></eds-select></div><div class="form-grid"><eds-number-input id="new-budget" label="Budget ($)" min="0" value="10000"></eds-number-input><eds-date-picker id="new-date" label="Launch date"></eds-date-picker></div><eds-textarea id="new-notes" label="Campaign brief" placeholder="What would you like to achieve?" rows="3"></eds-textarea><eds-switch id="new-launch" label="Mark as active"></eds-switch></div><div slot="footer" class="inline-actions"><eds-button variant="secondary" data-action="cancel">Cancel</eds-button><eds-button data-action="save">Create campaign</eds-button></div></eds-modal>
 <eds-drawer id="detail-drawer" heading="Campaign details" side="right"><div id="detail-content"></div></eds-drawer>
 <eds-drawer id="notifications" heading="Your notifications" side="right"><eds-alert variant="success" title="You're up to date">All campaigns are delivering within their planned budgets.</eds-alert><div class="notice"><eds-avatar name="Maya Poluru" size="sm"></eds-avatar><div><strong>Maya Poluru scheduled the fall edit</strong><p>September 18 at 9:00 AM · Email newsletter</p></div></div><div class="notice"><eds-avatar name="Rohan Poluru" size="sm"></eds-avatar><div><strong>The next chapter is now active</strong><p>Your product launch campaign is underway.</p></div></div></eds-drawer>`;}
 toggleSidebar(force){const open=force??!this.classList.contains('sidebar-open');this.classList.toggle('sidebar-open',open);this.querySelector('.sidebar').inert=!open;this.querySelector('#sidebar-toggle').setAttribute('aria-expanded',open);}
 renderPage(){this.route=location.hash.split('/')[1]||'overview';if(!nav.some(n=>n[0]===this.route))this.route='overview';const label=nav.find(n=>n[0]===this.route)[2];this.querySelector('#page-title').textContent=this.route==='overview'?'Good morning, Anika':label;this.querySelector('#page-description').textContent={overview:'A clear view of what’s working. And what’s next.',campaigns:'Big ideas. Thoughtful execution. Every campaign, in one place.',audiences:'Get to know the people behind your performance.',calendar:'Keep your story moving, one thoughtful moment at a time.',budgets:'Make every marketing dollar work a little harder.',channels:'The right message. The right channel. Measurable results.'}[this.route];document.title=`${label} · Meridian`;this.querySelectorAll('[data-route]').forEach(a=>{a.classList.toggle('active',a.dataset.route===this.route);a.setAttribute('aria-current',a.dataset.route===this.route?'page':'false');});this.querySelectorAll('.sidebar a').forEach(a=>a.classList.toggle('active',a.hash===`#/${this.route}`));this.querySelector('#page-content').innerHTML=this.route==='overview'?this.overview():this.route==='campaigns'?this.campaignTable(false):this.route==='audiences'?this.audiences():this.route==='calendar'?this.calendar():this.route==='budgets'?this.budgets():this.channelPage();}
 stats(){const prev=this.period==='Last month';return `<section class="stats-grid">${[['Campaign revenue',prev?'$112,480':'$128,640','14.4','currency-dollar','Revenue attributed to campaigns'],['Active campaigns',String(this.campaigns.filter(c=>c.status==='Active').length),'2','megaphone','Across 5 marketing channels'],['Audience reached',prev?'742.8K':'864.2K','16.3','people','People connecting with your brand'],['Return on ad spend',prev?'3.8x':'4.6x','21.1','graph-up-arrow','For every dollar you invest']].map(([label,value,delta,i,caption],n)=>`<eds-card class="stat-card"><div class="stat-label">${label}<span class="stat-icon">${icon(i)}</span></div><div class="stat-value">${value}<span class="delta">${icon('arrow-up-right')}${n===1?'+2':delta+'%'}</span></div><div class="stat-bottom">${caption}<svg viewBox="0 0 90 25" aria-hidden="true"><path d="M1 23 L12 18 L22 21 L34 12 L44 16 L54 8 L65 11 L76 4 L89 1"/></svg></div></eds-card>`).join('')}</section>`;}
 overview(){return `${this.stats()}<div class="analytics-grid">${this.performance()}${this.channelCard()}</div>${this.campaignTable(true)}<div class="bottom-grid">${this.upcoming()}${this.budgetCard()}</div>`;}
 performance(){let values=this.metric==='Revenue'?['$40k','$30k','$20k','$10k','$0']:['40k','30k','20k','10k','0'];return `<eds-card class="performance-card"><div class="card-heading"><div><h2>Performance over time</h2><p>A little momentum goes a long way.</p></div><div class="segmented" aria-label="Chart metric">${['Revenue','Conversions'].map(x=>`<button data-metric="${x}" class="${this.metric===x?'selected':''}" aria-pressed="${this.metric===x}">${x}</button>`).join('')}</div></div><div class="chart-legend"><span><i class="legend-line navy"></i>${this.period==='Last month'?'August':'September'} 2026</span><span><i class="legend-line dashed"></i>Previous month</span><strong>${this.metric==='Revenue'?(this.period==='Last month'?'$112,480':'$128,640'):'8,426'} <small>↗ 14.4%</small></strong></div><div class="line-chart"><div class="y-axis">${values.map(x=>`<span>${x}</span>`).join('')}</div><svg viewBox="0 0 800 185" preserveAspectRatio="none" role="img" aria-label="${this.metric} increased over the selected month, exceeding the previous month"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#738aaa" stop-opacity=".22"/><stop offset="100%" stop-color="#738aaa" stop-opacity="0"/></linearGradient></defs>${[10,50,90,130,170].map(y=>`<line x1="0" x2="800" y1="${y}" y2="${y}" stroke="#edf0f4"/>`).join('')}<path d="M0 158 C30 158 37 143 65 145 S110 160 138 140 S175 107 205 120 S245 145 280 123 S328 94 363 105 S407 109 439 84 S480 115 515 87 S557 74 590 80 S630 56 668 71 S710 47 742 56 S780 37 800 45" fill="none" stroke="#b7c4d5" stroke-width="2" stroke-dasharray="5 5"/><path d="M0 145 C30 147 37 121 65 126 S105 135 138 107 S180 122 205 91 S246 105 280 78 S325 95 363 65 S413 89 439 57 S487 78 515 44 S563 60 590 30 S640 56 668 24 S706 43 742 14 S776 25 800 9 L800 185 L0 185Z" fill="url(#area)"/><path d="M0 145 C30 147 37 121 65 126 S105 135 138 107 S180 122 205 91 S246 105 280 78 S325 95 363 65 S413 89 439 57 S487 78 515 44 S563 60 590 30 S640 56 668 24 S706 43 742 14 S776 25 800 9" fill="none" stroke="#1a2a4f" stroke-width="2.8"/></svg></div><div class="x-axis">${['Sep 01','Sep 05','Sep 10','Sep 15','Sep 20','Sep 25','Sep 30'].map(x=>`<span>${this.period==='Last month'?x.replace('Sep','Aug'):x}</span>`).join('')}</div></eds-card>`;}
 channelCard(){return `<eds-card><div class="card-heading"><div><h2>Channel mix</h2><p>How your audience finds you.</p></div><a class="icon-link" href="#/channels" aria-label="View channel performance">${icon('arrow-up-right')}</a></div><div class="channel-summary"><div class="donut"><div><strong>101K</strong><span>Total visits</span></div></div><div class="donut-summary"><span>Working together.</span><strong>Growing further.</strong><p>5 channels.<br>One connected story.</p></div></div><div class="channel-list">${channels.map(([i,n,v,r,p,c])=>`<div><span class="legend-dot" style="background:${c}"></span><span>${n}</span><strong>${v}</strong><small>${p}%</small></div>`).join('')}</div></eds-card>`;}
 campaignTable(compact){const rows=this.campaigns.filter(c=>(this.status==='All campaigns'||c.status===this.status)&&`${c.name} ${c.owner} ${c.channel}`.toLowerCase().includes(this.query.toLowerCase()));return `<eds-card class="campaign-card"><div class="card-heading"><div class="title-with-count"><h2>${compact?'Your campaigns':'Campaign workspace'}</h2><span class="count-badge">${this.campaigns.length}</span></div><a class="text-link" href="${compact?'#/campaigns':'#/calendar'}">${compact?'View all campaigns':'Open content calendar'} ${icon('arrow-right')}</a></div><div class="table-toolbar"><div class="filter-tabs">${['All campaigns','Active','Scheduled','Draft'].map(s=>`<button class="${this.status===s?'active':''}" data-status="${s}">${s}${s==='Active'?` <span>${this.campaigns.filter(c=>c.status==='Active').length}</span>`:''}</button>`).join('')}</div><span class="table-note">${this.query?`Matching “${escape(this.query)}”`:`${rows.length} campaigns`}</span></div><div class="table-scroll"><table><thead><tr><th class="check-col"><eds-checkbox id="select-all" ><span class="sr-only">Select all campaigns</span></eds-checkbox></th><th>Campaign name</th><th>Channel</th><th>Status</th><th>Budget spent</th><th>Reach</th><th>Conversion</th><th>Owner</th><th></th></tr></thead><tbody>${rows.map(c=>`<tr><td><eds-checkbox class="row-check" ><span class="sr-only">Select ${escape(c.name)}</span></eds-checkbox></td><td><button class="campaign-name" data-campaign="${escape(c.name)}"><span class="campaign-art ${c.color}">${icon(c.icon)}</span><span><strong>${escape(c.name)}</strong><small>${escape(c.desc)}</small></span></button></td><td><span class="channel-label">${icon(c.icon)}${escape(c.channel)}</span></td><td>${badge(c.status)}</td><td class="budget-cell"><strong>${money(c.spent)} <small>/ ${money(c.budget)}</small></strong><eds-progress-bar value="${c.budget?c.spent/c.budget*100:0}" aria-label="Budget used"></eds-progress-bar></td><td>${c.reach}</td><td>${c.rate}</td><td><eds-tooltip content="${escape(c.owner)}"><eds-avatar name="${escape(c.owner)}" size="sm"></eds-avatar></eds-tooltip></td><td><button class="row-more" data-campaign="${escape(c.name)}" aria-label="Details for ${escape(c.name)}">${icon('three-dots')}</button></td></tr>`).join('')||'<tr><td colspan="9" class="empty">No campaigns match. Try another search or status.</td></tr>'}</tbody></table></div><div class="table-footer"><span id="selection-count">Showing ${rows.length} of ${this.campaigns.length} campaigns</span><span>${icon('info-circle')} All amounts in USD</span></div></eds-card>`;}
 upcoming(){return `<eds-card><div class="card-heading"><div><h2>Coming up next</h2><p>A well-planned week starts here.</p></div><a href="#/calendar" class="text-link">View calendar ${icon('arrow-right')}</a></div><div class="upcoming-list">${events.map(([day,dow,title,type,time,i,owner])=>`<button class="event-row" data-event="${title}"><span class="event-date"><small>${dow}</small><strong>${day}</strong></span><span class="event-info"><strong>${title}</strong><small>${icon(i)} ${type} <span>·</span> ${time}</small></span><eds-avatar name="${owner}" size="sm"></eds-avatar><span class="event-arrow">${icon('chevron-right')}</span></button>`).join('')}</div></eds-card>`;}
 budgetCard(){return `<eds-card class="budget-overview"><div class="card-heading"><div><h2>Budget, in balance</h2><p>Room to make your next move.</p></div><a href="#/budgets" class="icon-link" aria-label="View budgets">${icon('arrow-up-right')}</a></div><div class="budget-total"><strong>$34,180</strong><span>of $77,500 allocated</span><eds-badge variant="success" pill>On track</eds-badge></div><div class="budget-track"><span></span><span></span><span></span></div><div class="budget-key"><span><i class="legend-dot navy"></i>Spent <strong>44.1%</strong></span><span><i class="legend-dot light"></i>Remaining <strong>$43,320</strong></span></div><div class="budget-tip">${icon('check2-circle')} Looking good. Your spend is within plan.</div></eds-card>`;}
 audiences(){return `<div class="audience-intro"><div><span class="eyebrow">MEANINGFUL CONNECTIONS</span><h2>Right people. Real possibilities.</h2><p>Thoughtfully curated segments for every stage of your customer’s journey.</p></div><span class="audience-big">864.2K <small>people reached this month</small></span></div><div class="audience-grid">${[['Brand explorers','New visitors discovering Meridian','284,600','Anika Poluru','compass','peach'],['Everyday enthusiasts','Engaged subscribers and repeat visitors','192,400','Maya Poluru','heart','mint'],['Meridian insiders','Loyal customers with 3+ purchases','86,200','Arjun Poluru','stars','lavender']].map(([n,d,v,o,i,c])=>`<eds-card><span class="campaign-art ${c}">${icon(i)}</span><h2 class="audience-title">${n}</h2><p class="muted">${d}</p><strong class="audience-size">${v}</strong><p class="muted">Members in segment</p><eds-divider></eds-divider><div class="audience-owner"><eds-avatar name="${o}" size="sm"></eds-avatar><span>${o}</span><eds-badge variant="success" pill>Healthy</eds-badge></div></eds-card>`).join('')}</div><div class="bottom-grid">${this.channelCard()}${this.upcoming()}</div>`;}
 calendar(){return `<eds-card><div class="card-heading"><div><h2>September 2026</h2><p>Your next chapter, thoughtfully scheduled.</p></div><eds-badge variant="info" pill>3 upcoming publications</eds-badge></div><div class="calendar-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="calendar-day-name">${d}</div>`).join('')}${Array.from({length:35},(_,i)=>{const d=i;return `<div class="calendar-day ${d===16?'today':''} ${d<1||d>30?'outside':''}"><span>${d<1?31:d>30?d-30:d}</span>${events.filter(e=>+e[0]===d).map(e=>`<button data-event="${e[2]}"><small>${e[4]}</small>${e[2]}</button>`).join('')}</div>`}).join('')}</div></eds-card>`;}
 budgets(){return `<div class="bottom-grid">${this.budgetCard()}<eds-card><div class="card-heading"><div><h2>Planned with purpose</h2><p>Allocation across your marketing portfolio.</p></div></div><div class="allocation-stat"><strong>$77,500</strong><span>Total campaign budget</span></div><eds-alert variant="info" title="September planning">$43,320 remains available within your allocated campaign budgets.</eds-alert></eds-card></div>${this.campaignTable(false)}`;}
 channelPage(){return `<div class="analytics-grid">${this.performance()}${this.channelCard()}</div><eds-card><div class="card-heading"><div><h2>Every channel, measured</h2><p>Understand the contribution behind each connection.</p></div></div><div class="table-scroll"><table><thead><tr><th>Channel</th><th>Visits</th><th>Traffic share</th><th>Return on ad spend</th><th>Performance</th></tr></thead><tbody>${channels.map(([i,n,v,r,p,c])=>`<tr><td><span class="channel-label">${icon(i)}<strong>${n}</strong></span></td><td>${v}</td><td><eds-progress-bar value="${p}" label="${p}% traffic share"></eds-progress-bar></td><td>${r}</td><td><eds-badge variant="success" pill>Above target</eds-badge></td></tr>`).join('')}</tbody></table></div></eds-card>`;}
 handleClick(e){const a=e.target.closest('[data-action]');if(a&&a.tagName!=='EDS-BUTTON')this.handleAction(a.dataset.action,a);const status=e.target.closest('[data-status]');if(status){this.status=status.dataset.status;this.renderPage();}const metric=e.target.closest('[data-metric]');if(metric){this.metric=metric.dataset.metric;this.renderPage();}const row=e.target.closest('[data-campaign]');if(row)this.openCampaign(row.dataset.campaign);const event=e.target.closest('[data-event]');if(event){const item=events.find(x=>x[2]===event.dataset.event);this.querySelector('#detail-drawer').heading='Publication details';this.querySelector('#detail-content').innerHTML=`<span class="eyebrow">SEPTEMBER ${item[0]}, 2026</span><h2 class="detail-title">${item[2]}</h2>${badge('Scheduled')}<p class="detail-copy">${item[3]} · ${item[4]}</p><eds-divider></eds-divider><div class="notice"><eds-avatar name="${item[6]}"></eds-avatar><div><strong>${item[6]}</strong><p>Content owner</p></div></div>`;this.querySelector('#detail-drawer').show();}}
 handleAction(action){if(action==='sidebar')this.toggleSidebar();if(action==='new')this.querySelector('#create-modal').show();if(action==='cancel')this.querySelector('#create-modal').close();if(action==='notifications')this.querySelector('#notifications').show();if(action==='save')this.saveCampaign();if(action==='export')this.exportReport();if(action==='profile'){this.querySelector('#detail-drawer').heading='Your workspace';this.querySelector('#detail-content').innerHTML='<eds-avatar name="Anika Poluru" size="lg"></eds-avatar><h2 class="detail-title">Anika Poluru</h2><p>Marketing director · Meridian Studio</p><eds-divider></eds-divider><p class="muted">Sample marketing workspace</p><eds-badge variant="success" pill>Team member</eds-badge>';this.querySelector('#detail-drawer').show();}}
 saveCampaign(){const name=this.querySelector('#new-name');if(!name.value.trim()){name.invalid=true;name.errorMessage='Enter a campaign name.';return;}const budget=Number(this.querySelector('#new-budget').value);if(!Number.isFinite(budget)||budget<0){showToast({message:'Enter a valid budget of zero or more.',variant:'warning'});return;}this.campaigns.unshift({name:name.value.trim(),desc:'New campaign · '+(this.querySelector('#new-date').value||'Launch date to be set'),channel:this.querySelector('#new-channel').value,owner:this.querySelector('#new-owner').value,status:this.querySelector('#new-launch').checked?'Active':'Draft',budget,spent:0,reach:'—',rate:'—',icon:'megaphone',color:'blue',notes:this.querySelector('#new-notes').value});name.value='';name.invalid=false;this.status='All campaigns';this.query='';this.querySelector('#campaign-search').value='';this.querySelector('#create-modal').close();this.querySelector('.nav-count').textContent=this.campaigns.length;this.renderPage();showToast({message:'Campaign created in this sample workspace.',variant:'success'});}
 openCampaign(name){const c=this.campaigns.find(c=>c.name===name);this.querySelector('#detail-drawer').heading='Campaign details';this.querySelector('#detail-content').innerHTML=`<span class="campaign-art ${c.color}">${icon(c.icon)}</span><h2 class="detail-title">${escape(c.name)}</h2><p class="muted">${escape(c.desc)}</p>${badge(c.status)}<eds-divider></eds-divider><div class="detail-stats"><div><span>Budget</span><strong>${money(c.budget)}</strong></div><div><span>Spent</span><strong>${money(c.spent)}</strong></div><div><span>Reach</span><strong>${c.reach}</strong></div><div><span>Conversion</span><strong>${c.rate}</strong></div></div><eds-progress-bar value="${c.budget?c.spent/c.budget*100:0}" label="Budget used" show-value></eds-progress-bar><div class="notice"><eds-avatar name="${escape(c.owner)}"></eds-avatar><div><strong>${escape(c.owner)}</strong><p>Campaign owner · ${escape(c.channel)}</p></div></div>${c.notes?`<p>${escape(c.notes)}</p>`:''}`;this.querySelector('#detail-drawer').show();}
 exportReport(){const csv=[['Campaign','Channel','Owner','Status','Budget','Spent','Reach','Conversion'],...this.campaigns.map(c=>[c.name,c.channel,c.owner,c.status,c.budget,c.spent,c.reach,c.rate])].map(row=>row.map(v=>'"'+String(v).replace(/"/g,'""')+'"').join(',')).join('\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='meridian-campaign-report.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast({message:'Campaign report exported.',variant:'success'});}
}
customElements.define('meridian-shell',MeridianShell);
