import { showToast } from '@poluru-labs/enterprise-design-system-wc';
const icon=(name)=>`<i class="bi bi-${name}" aria-hidden="true"></i>`;
const escape=(s)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav=[['overview','grid','Overview'],['students','people','Students'],['courses','book','Courses'],['enrollment','person-plus','Enrollment'],['attendance','calendar-check','Attendance'],['faculty','person-video3','Faculty'],['outcomes','bar-chart-line','Academic outcomes']];
const seed=[['Aarav Poluru','Computer Science','Year 2','Active',96],['Anika Poluru','Business Administration','Year 1','Active',94],['Rohan Poluru','Mechanical Engineering','Year 3','Active',89],['Ishita Poluru','Visual Communication','Year 2','Pending',92],['Vihaan Poluru','Computer Science','Year 1','Active',98],['Sahana Poluru','Business Administration','Year 3','Active',91],['Dev Poluru','Mechanical Engineering','Year 2','Pending',85],['Kavya Poluru','Visual Communication','Year 1','Active',97]].map((a,i)=>({name:a[0],course:a[1],year:a[2],status:a[3],attendance:a[4],id:`CO-${2026001+i}`}));
const courses=[['Computer Science','CS','Arjun Poluru',1248,92,'#dce8e0'],['Business Administration','BA','Mira Poluru',986,85,'#f5e8cc'],['Mechanical Engineering','ME','Nikhil Poluru',842,78,'#e0e8f2'],['Visual Communication','VC','Priya Poluru',624,88,'#eee2e9']];
const events=[['18','SEP','Fall orientation','09:00 AM · Main auditorium','gold'],['21','SEP','Faculty council meeting','11:30 AM · Conference room A','green'],['24','SEP','Mid-semester assessments','All day · All departments','blue']];
const card=(body,cls='')=>`<eds-card class="${cls}">${body}</eds-card>`;
const head=(title,sub,action='')=>`<div class="panel-head"><div><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div>${action}</div>`;
class CampusApp extends HTMLElement{
 connectedCallback(){this.students=[...seed];this.page=1;this.query='';this.status='All students';this.range='semester';this.render();this.route();this.onRoute=()=>this.route();window.addEventListener('hashchange',this.onRoute);this.onKey=e=>{if(e.key==='Escape')this.closeMega();if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();this.querySelector('#global-search').shadowRoot?.querySelector('input')?.focus();}};document.addEventListener('keydown',this.onKey);}
 disconnectedCallback(){window.removeEventListener('hashchange',this.onRoute);document.removeEventListener('keydown',this.onKey);}
 render(){this.innerHTML=`
 <aside class="sidebar"><a class="brand" href="#/overview"><span class="brand-symbol">${icon('mortarboard')}</span><span>Campus<span class="brand-one">One</span><small>EDUCATION WORKSPACE</small></span></a>
 <div class="campus-switch">${icon('buildings')}<span><strong>Westbridge University</strong><small>Main campus</small></span>${icon('chevron-expand')}</div>
 <div class="nav-caption">WORKSPACE</div><nav>${nav.map(([id,ic,label])=>`<a href="#/${id}" data-nav="${id}">${icon(ic)}<span>${label}</span>${id==='enrollment'?'<span class="nav-count">24</span>':''}</a>`).join('')}</nav>
 <div class="nav-caption second">MANAGE</div><nav><a href="#/reports" data-nav="reports">${icon('file-earmark-bar-graph')}<span>Reports</span></a><a href="#/calendar" data-nav="calendar">${icon('calendar3')}<span>Academic calendar</span></a><a href="#/settings" data-nav="settings">${icon('gear')}<span>Settings</span></a></nav>
 <div class="sidebar-bottom"><div class="semester-card"><span>${icon('sun')} FALL SEMESTER 2026</span><strong>A new term. New possibilities.</strong><small>Sep 01 – Dec 18, 2026</small><eds-progress-bar value="14" label="Semester progress"></eds-progress-bar><div>Week 3 of 16 <span>14%</span></div></div><a class="help" href="#/help">${icon('question-circle')} Help & resources ${icon('arrow-up-right')}</a><div class="side-profile"><eds-avatar name="Mira Poluru" size="sm"></eds-avatar><div><strong>Mira Poluru</strong><small>Campus administrator</small></div><a href="#/settings" aria-label="Profile settings">${icon('chevron-expand')}</a></div></div></aside>
 <div class="workspace"><header class="topbar"><div class="header-left"><button class="icon-button mobile-menu" aria-label="Toggle sidebar">${icon('list')}</button><span class="header-campus">${icon('buildings')} Main campus</span><span class="header-line"></span><button id="mega-toggle" aria-expanded="false" aria-controls="mega-menu">Explore campus ${icon('chevron-down')}</button></div><div class="header-right"><div class="global-search"><eds-search id="global-search" placeholder="Search anything..."></eds-search><eds-kbd keys="⌘ K"></eds-kbd></div><eds-tooltip content="Notifications"><button id="notifications" class="icon-button notification" aria-label="Notifications">${icon('bell')}<b></b></button></eds-tooltip><span class="header-line"></span><eds-avatar name="Mira Poluru" size="sm"></eds-avatar></div></header>
 <div id="mega-menu" class="mega-menu" hidden><div><span class="eyebrow">CAMPUS DIRECTORY</span><h2>Everything in one place.</h2><p>Connect the people, programs, and moments that make your campus.</p><eds-badge label="Fall 2026" variant="neutral"></eds-badge></div><div><h3>Academics</h3>${nav.filter(x=>['courses','faculty','outcomes'].includes(x[0])).map(x=>`<a href="#/${x[0]}">${icon(x[1])}${x[2]} ${icon('arrow-right')}</a>`).join('')}</div><div><h3>Student services</h3>${nav.filter(x=>['students','enrollment','attendance'].includes(x[0])).map(x=>`<a href="#/${x[0]}">${icon(x[1])}${x[2]} ${icon('arrow-right')}</a>`).join('')}</div><div><h3>Planning & resources</h3><a href="#/calendar">${icon('calendar3')}Academic calendar</a><a href="#/reports">${icon('file-earmark-text')}Reports & exports</a><a href="#/help">${icon('question-circle')}Help center</a></div></div>
 <main id="view" tabindex="-1"></main><footer class="page-footer"><span>© 2026 CampusOne. Every student, a possibility.</span><span><span class="status-dot"></span> All systems operational <span class="footer-divider">|</span> Sample campus data</span></footer></div>
 <eds-modal id="enroll-modal" heading="Enroll a student" close-on-backdrop close-on-escape><div class="form-stack"><p>Add a student to the Fall 2026 intake.</p><eds-input id="student-name" label="Full name" placeholder="e.g. Tara Poluru" required></eds-input><eds-input id="student-email" label="Email address" type="email" placeholder="tara@example.edu" required></eds-input><eds-select id="student-course" label="Program" required></eds-select><eds-select id="student-year" label="Academic year"></eds-select><eds-textarea id="student-notes" label="Notes (optional)" rows="2" placeholder="Enrollment notes"></eds-textarea><p id="form-error" role="alert" class="error"></p></div><div slot="footer" class="actions"><eds-button id="cancel-enroll" variant="secondary">Cancel</eds-button><eds-button id="save-enroll" variant="primary">Enroll student</eds-button></div></eds-modal>
 <eds-drawer id="notification-drawer" heading="Campus notifications" side="right"><div class="notification-item">${icon('person-plus')}<div><strong>Fall enrollment is open</strong><p>24 applications are ready for review.</p><a href="#/enrollment">Review applications →</a></div></div><eds-divider></eds-divider><div class="notification-item">${icon('calendar-event')}<div><strong>Orientation is this Friday</strong><p>September 18 at 9:00 AM. Main auditorium.</p></div></div></eds-drawer>
 <eds-modal id="detail-modal" heading="Student profile"><div id="detail-body"></div></eds-modal>`;
 this.querySelector('#student-course').options=courses.map(x=>({label:x[0],value:x[0]}));this.querySelector('#student-course').value=courses[0][0];this.querySelector('#student-year').options=[1,2,3,4].map(x=>({label:`Year ${x}`,value:`Year ${x}`}));this.querySelector('#student-year').value='Year 1';
 this.querySelector('#mega-toggle').onclick=()=>{const menu=this.querySelector('#mega-menu');menu.hidden=!menu.hidden;this.querySelector('#mega-toggle').setAttribute('aria-expanded',!menu.hidden);};
 this.querySelector('.mobile-menu').onclick=()=>this.classList.toggle('sidebar-visible');
 this.querySelector('#notifications').onclick=()=>this.querySelector('#notification-drawer').show();
 this.querySelector('#cancel-enroll').addEventListener('eds-click',()=>this.querySelector('#enroll-modal').close());this.querySelector('#save-enroll').addEventListener('eds-click',()=>this.saveStudent());
 this.querySelector('#global-search').addEventListener('eds-input',e=>{this.query=e.detail.value;this.page=1;if(this.current!=='students')location.hash='/students';else this.renderStudentsTable();});
 this.addEventListener('click',e=>{const act=e.target.closest('[data-action]');if(act){if(act.dataset.action==='enroll')this.querySelector('#enroll-modal').show();if(act.dataset.action==='export')this.export();if(act.dataset.action==='profile')this.profile(act.dataset.id);if(act.dataset.action==='event')this.eventDetail(Number(act.dataset.id));}if(e.target.closest('#mega-menu a'))this.closeMega();});
 }
 closeMega(){this.querySelector('#mega-menu').hidden=true;this.querySelector('#mega-toggle').setAttribute('aria-expanded','false');}
 route(){this.current=location.hash.replace('#/','')||'overview';this.closeMega();this.classList.remove('sidebar-visible');this.querySelector('#notification-drawer').close();this.querySelectorAll('[data-nav]').forEach(a=>{a.classList.toggle('active',a.dataset.nav===this.current);a.setAttribute('aria-current',a.dataset.nav===this.current?'page':'false');});const label=nav.find(x=>x[0]===this.current)?.[2]||({reports:'Reports',calendar:'Academic calendar',settings:'Settings',help:'Help & resources'}[this.current])||'Overview';document.title=`${label} · CampusOne`;this.querySelector('#view').innerHTML=this.current==='overview'?this.overview():this.otherView(label);this.hydrateView();}
 title(title,subtitle){return `<div class="breadcrumb">Workspace <span>/</span> <strong>${title}</strong></div><div class="page-heading"><div><h1>${title==='Overview'?'Campus overview':title}<span class="heading-dot">.</span></h1><p>${subtitle}</p></div><div class="actions"><eds-button variant="secondary" data-action="export" icon="download">Export report</eds-button><eds-button variant="primary" data-action="enroll" icon="plus">Enroll student</eds-button></div></div>`;}
 overview(){return `${this.title('Overview','A connected view of your campus. Every student, every milestone.')}<div class="welcome-strip"><div class="welcome-icon">${icon('sun')}</div><div><strong>A good day to make a difference, Mira.</strong><span>Here’s what’s happening across Westbridge University.</span></div><div class="welcome-date">${icon('calendar3')} Wednesday, September 16, 2026</div></div><div class="section-toolbar"><div class="section-tabs"><button class="selected" data-overview-tab="overview">Overview</button><button data-overview-tab="academic">Academic performance</button><button data-overview-tab="engagement">Student engagement</button></div><div class="term-chip">${icon('calendar-range')} Fall semester 2026 <eds-badge label="In progress" variant="success" size="sm"></eds-badge></div></div><div id="overview-content">${this.overviewContent()}</div>`;}
 overviewContent(){return `<div class="stats-grid">${[['Total students','8,542','+8.2%','vs. last semester','people','M0 32 L13 28 L24 30 L36 18 L49 24 L62 14 L76 17 L90 6'],['Active courses','148','+12','new this semester','book','M0 30 L15 30 L28 23 L41 26 L53 15 L68 15 L80 5 L90 5'],['Attendance rate','94.6%','+2.4%','vs. last semester','calendar-check','M0 29 L12 19 L25 23 L39 13 L51 21 L65 12 L78 15 L90 5'],['Graduation rate','92.8%','+3.1%','vs. last year','mortarboard','M0 31 L13 29 L25 25 L39 26 L52 17 L65 19 L78 8 L90 4']].map(([t,v,d,s,i,path])=>card(`<div class="stat-top"><span>${t}</span><span class="stat-icon">${icon(i)}</span></div><div class="stat-number">${v}<svg viewBox="0 0 94 42" aria-hidden="true"><path d="${path}" fill="none" stroke="#739081" stroke-width="2"/></svg></div><div class="stat-bottom"><span>${icon('arrow-up-right')} ${d}</span> ${s}</div>`,'stat-card')).join('')}</div>
 <div class="analytics-grid">${card(`${head('Enrollment overview','Student enrollment throughout the academic year',`<div class="segmented"><button class="active" data-range="semester">Semester</button><button data-range="year">Year</button></div>`)}<div class="chart-summary"><strong id="enrollment-total">8,542</strong><eds-badge label="↗ 8.2%" variant="success" size="sm"></eds-badge><span>total enrolled students</span><div class="chart-legend"><span><b class="legend-green"></b>This year</span><span><b class="legend-gold"></b>Last year</span></div></div><div id="enrollment-chart">${this.chart()}</div><div class="chart-foot">${icon('info-circle')} Enrollment is up <strong>648 students</strong> compared to last year.</div>`,'enrollment-chart')}${card(`${head('Attendance snapshot','A little presence makes a big difference.',`<eds-tooltip content="Attendance for September 14–18"><span class="muted">${icon('info-circle')}</span></eds-tooltip>`)}<div class="attendance-main"><div class="attendance-ring"><div><strong>94.6<span>%</span></strong><small>Average attendance</small></div></div><div class="attendance-legend"><span><b style="background:#315643"></b>Present <strong>94.6%</strong></span><span><b style="background:#ebcb90"></b>Absent <strong>3.2%</strong></span><span><b style="background:#e7ebe4"></b>On leave <strong>2.2%</strong></span></div></div><div class="week-bars">${[94,96,95,93,95].map((v,i)=>`<div><div class="week-bar"><span style="height:${v}%"></span></div><small>${['Mon','Tue','Wed','Thu','Fri'][i]}</small></div>`).join('')}</div><div class="attendance-foot"><span class="status-dot"></span> Above your 90% attendance goal <a href="#/attendance">${icon('arrow-right')}</a></div>`,'attendance-card')}</div>
 <div class="lower-grid">${card(`${head('Recent enrollments','Welcoming the next generation of possibility.',`<a class="text-link" href="#/students">View all students ${icon('arrow-right')}</a>`)}<div id="student-table">${this.studentTable(this.students.slice(0,4))}</div><div class="table-footer"><span>Showing 4 of ${this.students.length} sample enrollments</span><a href="#/enrollment">Manage enrollments ${icon('arrow-up-right')}</a></div>`,'student-panel')}${card(`${head('Coming up','Your campus, on the calendar.',`<a href="#/calendar" class="icon-button" aria-label="View calendar">${icon('arrow-up-right')}</a>`)}<div class="events">${events.map((x,i)=>`<button class="event" data-action="event" data-id="${i}"><span class="event-date ${x[4]}"><strong>${x[0]}</strong><small>${x[1]}</small></span><span><strong>${x[2]}</strong><small>${x[3]}</small></span>${icon('chevron-right')}</button>`).join('')}</div><a class="calendar-link" href="#/calendar">View academic calendar ${icon('arrow-right')}</a>`,'events-card')}</div><div class="bottom-grid">${card(`${head('Programs at a glance','Learning that moves the world forward.',`<a class="text-link" href="#/courses">Explore courses ${icon('arrow-right')}</a>`)}<div class="programs">${courses.slice(0,3).map(x=>`<a href="#/courses" class="program"><span class="program-icon" style="background:${x[5]}">${icon(x[1]==='CS'?'code-slash':x[1]==='BA'?'briefcase':'gear-wide-connected')}</span><strong>${x[0]}</strong><small>${x[3].toLocaleString()} students · ${x[2]}</small><eds-progress-bar value="${x[4]}" label="Course completion"></eds-progress-bar><div><span>Course completion</span><b>${x[4]}%</b></div></a>`).join('')}</div>`)}<div class="outcome-banner"><span>${icon('mortarboard')} STUDENT SUCCESS</span><h2>Big dreams.<br>Measurable progress.</h2><p>92.8% of our students are on their way to their next chapter.</p><a href="#/outcomes">Explore academic outcomes ${icon('arrow-up-right')}</a></div></div>`;}
 chart(){const year=this.range==='year';return `<svg class="line-chart" viewBox="0 0 700 195" role="img" aria-label="Enrollment rose from ${year?'5,800 to 8,542 across 2026':'6,200 in August to 8,542 in December'}; previous year rose to 7,894."><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#537c61" stop-opacity=".16"/><stop offset="100%" stop-color="#537c61" stop-opacity="0"/></linearGradient></defs>${[25,65,105,145].map((y,i)=>`<text x="0" y="${y+4}">${['10k','8k','6k','4k'][i]}</text><line x1="38" x2="680" y1="${y}" y2="${y}" stroke="#eceee7" stroke-dasharray="4 5"/>`).join('')}<path d="M40 119 C90 117 112 82 165 86 S245 105 300 72 S378 80 424 52 S485 60 543 40 S612 30 676 27 L676 153 L40 153Z" fill="url(#area)"/><path d="M40 137 C98 133 113 108 165 117 S244 120 300 102 S373 106 424 88 S486 91 543 73 S624 80 676 55" fill="none" stroke="#dfbd7d" stroke-width="2.5" stroke-dasharray="5 5"/><path d="${year?'M40 137 C90 130 112 120 165 118 S245 102 300 95 S378 70 424 74 S485 40 543 47 S612 25 676 27':'M40 119 C90 117 112 82 165 86 S245 105 300 72 S378 80 424 52 S485 60 543 40 S612 30 676 27'}" fill="none" stroke="#315643" stroke-width="3"/><circle cx="676" cy="27" r="4" fill="#315643" stroke="white" stroke-width="2"/>${(year?['Jan','Mar','May','Jul','Sep','Dec']:['Aug','Sep','Oct','Nov','Dec','Jan']).map((s,i)=>`<text x="${40+i*126}" y="182" text-anchor="middle">${s}</text>`).join('')}</svg>`;}
 studentTable(rows){return `<div class="table-scroll"><table><thead><tr><th><eds-checkbox accessible-label="Select students" id="select-all"></eds-checkbox></th><th>Student name</th><th>Program</th><th>Year</th><th>Status</th><th></th></tr></thead><tbody>${rows.map((s,i)=>`<tr><td><eds-checkbox aria-label="Select ${escape(s.name)}"></eds-checkbox></td><td><button class="student-name" data-action="profile" data-id="${s.id}"><eds-avatar name="${escape(s.name)}" size="sm" style="--eds-color-brand-100:${['#f3e4d4','#e1e8de','#e5e5ef','#f2e1e6'][i%4]}"></eds-avatar><span><strong>${escape(s.name)}</strong><small>${s.id}</small></span></button></td><td>${escape(s.course)}</td><td>${s.year}</td><td><eds-badge label="${s.status}" variant="${s.status==='Active'?'success':'warning'}" size="sm" pill></eds-badge></td><td><button class="icon-button" aria-label="View ${escape(s.name)}" data-action="profile" data-id="${s.id}">${icon('three-dots')}</button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No students match your filters.</td></tr>'}</tbody></table></div>`;}
 otherView(label){const title=this.title(label,({students:'The people at the heart of your campus.',courses:'Purposeful programs. Meaningful learning.',faculty:'Meet the people shaping the next generation.',enrollment:'Give every new beginning a place to grow.',attendance:'A clear picture of student participation.',outcomes:'Follow every milestone on the path to graduation.',reports:'Campus insights, ready to share.',calendar:'Make room for the moments that matter.',settings:'Make CampusOne work for your campus.',help:'A little guidance, whenever you need it.'})[this.current]||'Your connected campus workspace.');let body='';
 if(['students','enrollment'].includes(this.current)){body=card(`<div class="directory-toolbar"><eds-search id="student-search" placeholder="Search students or programs" value="${escape(this.query)}"></eds-search><eds-select id="status-filter" aria-label="Filter student status"></eds-select><span class="muted" id="result-count"></span></div><div id="student-table"></div><div class="directory-footer"><eds-pagination id="student-pagination" page-size="5"></eds-pagination></div>`);}
 else if(this.current==='courses'||this.current==='faculty'){body=`<div class="course-grid">${courses.map((c,i)=>card(`${head(this.current==='faculty'?c[2]:c[0],this.current==='faculty'?c[0]+' · Department chair':'Undergraduate program',`<span class="program-icon" style="background:${c[5]}">${this.current==='faculty'?icon('person-video3'):c[1]}</span>`)}<div class="course-body"><eds-badge label="${this.current==='faculty'?'Available for advising':'Enrollment open'}" variant="success"></eds-badge><p>${this.current==='faculty'?'Office hours: Monday & Wednesday, 2–4 PM':`Led by ${c[2]} · ${24+i*6} active courses`}</p><div class="course-numbers"><strong>${c[3].toLocaleString()}<small>Enrolled students</small></strong><strong>${c[4]}%<small>Completion rate</small></strong></div><eds-progress-bar value="${c[4]}" label="Program completion" show-value></eds-progress-bar><eds-button variant="secondary" data-action="${this.current==='faculty'?'faculty':'enroll'}" data-index="${i}">${this.current==='faculty'?'View faculty details':'Enroll in program'}</eds-button></div>`)).join('')}</div>`;}
 else if(this.current==='attendance'||this.current==='outcomes'){body=`<div class="report-stats">${[['Average attendance','94.6%'],['On track to graduate','92.8%'],['Average GPA','3.62']].map(x=>card(`<span class="muted">${x[0]}</span><div class="stat-number">${x[1]}</div><eds-badge label="Above target" variant="success"></eds-badge>`)).join('')}</div>${card(head(this.current==='attendance'?'Attendance by student':'Academic progress by program','Fall semester 2026')+'<eds-data-table id="academic-table" sortable></eds-data-table>')}`;}
 else if(this.current==='calendar'){body=card(`${head('September 2026','Fall semester · Main campus')}<div class="calendar-grid">${['MON','TUE','WED','THU','FRI','SAT','SUN'].map(d=>`<strong>${d}</strong>`).join('')}${Array.from({length:35},(_,i)=>{let n=i;return `<div class="calendar-day ${n===16?'today':''}">${n>0&&n<=30?`<span>${n}</span>${events.filter(e=>+e[0]===n).map(e=>`<button data-action="event" data-id="${events.indexOf(e)}">${e[2]}</button>`).join('')}`:''}</div>`}).join('')}</div>`);}
 else if(this.current==='reports'){body=card(`${head('Campus reports','Export the current sample records as CSV.')}<div class="report-list">${['Student enrollment register','Attendance summary','Academic outcomes','Program directory'].map((t,i)=>`<div>${icon('file-earmark-bar-graph')}<span><strong>${t}</strong><small>Fall 2026 · Prepared by Mira Poluru</small></span><eds-button class="report-download" data-report="${i}" variant="secondary" icon="download">Download CSV</eds-button></div>`).join('')}</div>`);}
 else if(this.current==='settings'){body=card(`${head('Workspace preferences','Changes are saved in this browser.')}<div class="form-stack settings-form"><eds-input id="campus-name" label="Campus name" value="Westbridge University"></eds-input><eds-select id="settings-term" label="Academic term"></eds-select><eds-switch id="email-switch" label="Email notifications" checked></eds-switch><eds-switch id="digest-switch" label="Weekly attendance digest" checked></eds-switch><eds-divider></eds-divider><eds-button id="save-settings" variant="primary">Save preferences</eds-button><p id="settings-status" role="status"></p></div>`);}
 else{body=card(`${head('How can we help?','CampusOne support & resources')}<eds-accordion><eds-accordion-item heading="How do I enroll a student?"><p>Select Enroll student, enter their name and email, choose a program, and confirm. New records appear in the student directory for this session.</p></eds-accordion-item><eds-accordion-item heading="How do I export campus records?"><p>Open Reports and choose a CSV download. Student search and status filters also apply to the directory export.</p></eds-accordion-item><eds-accordion-item heading="About this workspace"><p>This is a sample campus workspace. All people are fictional and records are held in memory for this session.</p></eds-accordion-item></eds-accordion>`);}
 return title+body;}
 themeCards(){this.querySelectorAll('eds-card').forEach(async c=>{await c.updateComplete;if(!c.shadowRoot.querySelector('[data-campus-theme]')){const style=document.createElement('style');style.dataset.campusTheme='';style.textContent='.header,.footer,.media{display:none}.body{padding:20px!important}';c.shadowRoot.append(style);}});}
 hydrateView(){this.themeCards();this.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{this.range=b.dataset.range;this.querySelectorAll('[data-range]').forEach(x=>x.classList.toggle('active',x===b));this.querySelector('#enrollment-chart').innerHTML=this.chart();});this.querySelectorAll('[data-overview-tab]').forEach(b=>b.onclick=()=>{this.querySelectorAll('[data-overview-tab]').forEach(x=>x.classList.toggle('selected',x===b));const view=this.querySelector('#overview-content');if(b.dataset.overviewTab==='overview'){view.innerHTML=this.overviewContent();this.hydrateView();}else{view.innerHTML=`<div class="report-stats">${(b.dataset.overviewTab==='academic'?[['Graduation rate','92.8%'],['Average GPA','3.62'],['Course completion','88.4%']]:[['Attendance rate','94.6%'],['Student organizations','42'],['Campus event participation','76.2%']]).map(x=>card(`<span>${x[0]}</span><div class="stat-number">${x[1]}</div><eds-badge label="Above semester target" variant="success"></eds-badge>`)).join('')}</div>${card(head('Program performance','Fall semester 2026')+'<eds-data-table id="tab-table" sortable></eds-data-table>')}`;const table=this.querySelector('#tab-table');table.columns=[{key:'program',label:'Program'},{key:'students',label:'Students',sortable:true},{key:'completion',label:'Completion',sortable:true}];table.rows=courses.map(c=>({program:c[0],students:c[3],completion:c[4]+'%'}));this.themeCards();}});
 if(['students','enrollment'].includes(this.current)){const filter=this.querySelector('#status-filter');filter.options=['All students','Active','Pending'].map(x=>({label:x,value:x}));filter.value=this.status;filter.addEventListener('eds-change',e=>{this.status=e.detail.value;this.page=1;this.renderStudentsTable();});this.querySelector('#student-search').addEventListener('eds-input',e=>{this.query=e.detail.value;this.page=1;this.renderStudentsTable();});this.querySelector('#student-pagination').addEventListener('eds-change',e=>{this.page=e.detail.page;this.renderStudentsTable();});this.renderStudentsTable();}
 const academic=this.querySelector('#academic-table');if(academic){academic.columns=this.current==='attendance'?[{key:'name',label:'Student',sortable:true},{key:'course',label:'Program'},{key:'attendance',label:'Attendance %',sortable:true},{key:'status',label:'Enrollment'}]:[{key:'program',label:'Program'},{key:'owner',label:'Faculty lead'},{key:'students',label:'Enrolled',sortable:true},{key:'completion',label:'Completion %',sortable:true}];academic.rows=this.current==='attendance'?this.students:courses.map(c=>({program:c[0],owner:c[2],students:c[3],completion:c[4]}));}
 this.querySelectorAll('[data-action="faculty"]').forEach(b=>b.addEventListener('eds-click',()=>{const c=courses[+b.dataset.index];this.openDetail(c[2],`<eds-avatar name="${c[2]}" size="lg"></eds-avatar><h3>${c[0]}</h3><p>Department chair · Full-time faculty</p><p>Office hours: Monday & Wednesday, 2–4 PM</p><p>Office: Academic building, room ${210+Number(b.dataset.index)}</p>`);}));
 this.querySelectorAll('.report-download').forEach(b=>b.addEventListener('eds-click',()=>this.export(+b.dataset.report)));
 if(this.current==='settings'){const term=this.querySelector('#settings-term');term.options=[{label:'Fall 2026',value:'fall'},{label:'Spring 2027',value:'spring'}];term.value='fall';try{const prefs=JSON.parse(localStorage.getItem('campusone-preferences')||'null');if(prefs){this.querySelector('#campus-name').value=prefs.name;term.value=prefs.term;this.querySelector('#email-switch').checked=prefs.email;this.querySelector('#digest-switch').checked=prefs.digest;}}catch{}this.querySelector('#save-settings').addEventListener('eds-click',()=>{const prefs={name:this.querySelector('#campus-name').value.trim(),term:term.value,email:this.querySelector('#email-switch').checked,digest:this.querySelector('#digest-switch').checked};if(!prefs.name)return;try{localStorage.setItem('campusone-preferences',JSON.stringify(prefs));this.querySelector('.campus-switch strong').textContent=prefs.name;this.querySelector('#settings-status').textContent='Preferences saved.';}catch{this.querySelector('#settings-status').textContent='Browser storage is unavailable.';}});}
 this.wireCheckboxes();}
 filtered(){return this.students.filter(s=>(this.status==='All students'||s.status===this.status)&&`${s.name} ${s.course} ${s.id}`.toLowerCase().includes(this.query.toLowerCase()));}
 renderStudentsTable(){const filtered=this.filtered();this.querySelector('#student-table').innerHTML=this.studentTable(filtered.slice((this.page-1)*5,this.page*5));this.querySelector('#result-count').textContent=`${filtered.length} students`;this.querySelector('#student-pagination').total=filtered.length;this.querySelector('#student-pagination').page=this.page;this.wireCheckboxes();}
 wireCheckboxes(){this.querySelector('#select-all')?.addEventListener('eds-change',e=>this.querySelectorAll('tbody eds-checkbox').forEach(c=>c.checked=e.detail.checked));}
 saveStudent(){const name=this.querySelector('#student-name').value.trim(),email=this.querySelector('#student-email').value.trim();if(!name||!/^\S+@\S+\.\S+$/.test(email)){this.querySelector('#form-error').textContent='Enter a full name and a valid email address.';return;}this.students.unshift({name,email,course:this.querySelector('#student-course').value,year:this.querySelector('#student-year').value,status:'Active',attendance:0,id:`CO-${2026001+this.students.length}`});this.querySelector('#enroll-modal').close();this.querySelector('#student-name').value='';this.querySelector('#student-email').value='';this.querySelector('#form-error').textContent='';this.query='';this.status='All students';this.page=1;if(this.current==='students')this.route();else location.hash='/students';showToast({message:`${name} enrolled successfully`,variant:'success'});}
 openDetail(title,body){this.querySelector('#detail-modal').heading=title;this.querySelector('#detail-body').innerHTML=body;this.querySelector('#detail-modal').show();}
 profile(id){const s=this.students.find(x=>x.id===id);this.openDetail(s.name,`<div class="profile-detail"><eds-avatar name="${escape(s.name)}" size="lg"></eds-avatar><h3>${escape(s.name)}</h3><p>${s.id}</p><eds-badge label="${s.status}" variant="success"></eds-badge><eds-divider></eds-divider><dl><dt>Program</dt><dd>${escape(s.course)}</dd><dt>Academic year</dt><dd>${s.year}</dd><dt>Attendance</dt><dd>${s.attendance?`${s.attendance}%`:'No classes recorded yet'}</dd><dt>Faculty advisor</dt><dd>${courses.find(c=>c[0]===s.course)?.[2]||'Mira Poluru'}</dd></dl></div>`);}
 eventDetail(i){const e=events[i];this.openDetail(e[2],`<eds-badge label="${e[0]} September 2026" variant="neutral"></eds-badge><h3>${e[2]}</h3><p>${e[3]}</p><eds-divider></eds-divider><p>Organized by ${['Mira Poluru','Arjun Poluru','Priya Poluru'][i]}</p><p>${['Welcome our incoming students and meet the faculty. Please arrive 15 minutes before the session.','Department chairs will review semester priorities, course availability, and student support.','Assessment schedules are available from each department. Students should bring their campus ID.'][i]}</p>`);}
 export(type=0){let rows=this.filtered().map(s=>({Student:s.name,ID:s.id,Program:s.course,Year:s.year,Status:s.status,...(type===1?{Attendance:s.attendance}: {})}));if(type===2||type===3)rows=courses.map(c=>({Program:c[0],Faculty:c[2],Students:c[3],Completion:c[4]}));if(!rows.length){showToast({message:'No matching records to export.',variant:'warning'});return;}const cell=x=>'"'+String(x).replace(/"/g,'""')+'"';const csv=[Object.keys(rows[0]),...rows.map(Object.values)].map(r=>r.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=url;a.download=`campusone-${['enrollment','attendance','outcomes','programs'][type]}-fall-2026.csv`;a.click();URL.revokeObjectURL(url);showToast({message:'Report downloaded',variant:'success'});}
}
customElements.define('campus-app',CampusApp);
