import { showToast } from '@poluru-labs/enterprise-design-system-wc';
const icon = (name) => `<i class="bi bi-${name}" aria-hidden="true"></i>`;
const money = n => new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
const escape = s => String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const initialAccounts = [
 {id:'PT-10482',name:'Aarav Poluru',payer:'Blue Cross Blue Shield',service:'Sep 12, 2026',amount:1240,status:'Overdue',days:34,claim:'CLM-20841'},
 {id:'PT-10483',name:'Maya Poluru',payer:'Aetna',service:'Sep 11, 2026',amount:485,status:'Pending',days:12,claim:'CLM-20842'},
 {id:'PT-10484',name:'Rohan Poluru',payer:'UnitedHealthcare',service:'Sep 10, 2026',amount:2180,status:'Denied',days:28,claim:'CLM-20843'},
 {id:'PT-10485',name:'Anika Poluru',payer:'Medicare',service:'Sep 10, 2026',amount:0,received:760,status:'Paid',days:0,claim:'CLM-20844'},
 {id:'PT-10486',name:'Vihaan Poluru',payer:'Cigna',service:'Sep 09, 2026',amount:325,status:'Payment plan',days:18,claim:'CLM-20845'},
 {id:'PT-10487',name:'Isha Poluru',payer:'Aetna',service:'Sep 08, 2026',amount:1680,status:'Denied',days:41,claim:'CLM-20846'},
 {id:'PT-10488',name:'Dev Poluru',payer:'Medicare',service:'Sep 07, 2026',amount:940,status:'Pending',days:9,claim:'CLM-20847'},
 {id:'PT-10489',name:'Neha Poluru',payer:'Cigna',service:'Sep 06, 2026',amount:580,status:'Overdue',days:45,claim:'CLM-20848'}
];
const sections = ['Overview','Patient billing','Claims','Denials','Reimbursements','Collections'];
const navIcons = ['grid','receipt','file-earmark-medical','shield-exclamation','arrow-left-right','wallet2'];
const variant = s => ({Paid:'success',Pending:'info',Denied:'danger',Overdue:'warning','Payment plan':'neutral','In review':'info'})[s] || 'neutral';
export class CoveraApp extends HTMLElement {
 connectedCallback(){
  this.accounts=initialAccounts.map(a=>({...a}));this.payments=[];this.query='';this.status='All statuses';this.page=1;
  this.section=sections.includes(decodeURIComponent(location.hash.slice(2)))?decodeURIComponent(location.hash.slice(2)):'Overview';
  this.render(); this.onHash=()=>{const s=decodeURIComponent(location.hash.slice(2));if(sections.includes(s)&&s!==this.section)this.navigate(s);};window.addEventListener('hashchange',this.onHash);
 }
 disconnectedCallback(){window.removeEventListener('hashchange',this.onHash);}
 render(){this.innerHTML=`
 <header class="topbar"><div class="brand-group"><eds-tooltip content="Toggle sidebar"><eds-button id="nav-toggle" variant="tertiary" icon="menu" icon-only accessible-label="Show sidebar" aria-expanded="false"></eds-button></eds-tooltip><a class="brand" href="#/Overview"><span class="brand-symbol">${icon('intersect')}</span>Covera<span class="brand-divider"></span><span class="product-label">Revenue cycle</span></a></div>
 <div class="header-tools"><span class="demo"><span></span>Demo workspace</span><eds-tooltip content="Notifications"><eds-button id="notifications" variant="tertiary" icon="bell" icon-only accessible-label="Notifications"></eds-button></eds-tooltip><span class="header-divider"></span><eds-avatar name="Priya Poluru" size="sm"></eds-avatar><div class="user-copy"><strong>Priya Poluru</strong><small>Billing administrator</small></div></div></header>
 <aside class="sidebar" hidden><div class="sidebar-label">WORKSPACE</div>${sections.map((s,i)=>`<button data-nav="${s}">${icon(navIcons[i])}<span>${s}</span>${s==='Denials'?'<span class="nav-count">2</span>':''}</button>`).join('')}<div class="sidebar-bottom"><eds-divider></eds-divider><p>Covera Medical Group</p><small>Patient financial services</small></div></aside>
 <main id="view"><div class="page-heading"><div><div class="eyebrow">COVERA MEDICAL GROUP <span>/</span> FINANCIAL OPERATIONS</div><h1 id="page-title">Revenue cycle overview</h1><p id="page-subtitle">A clear view of your revenue. A better experience for your patients.</p></div><div class="heading-actions"><eds-button id="export" variant="secondary" icon="download">Export report</eds-button><eds-button id="payment" icon="plus">Record payment</eds-button></div></div>
 <div class="workspace-bar"><nav class="section-nav" aria-label="Revenue cycle">${sections.map(s=>`<button data-nav="${s}" class="${this.section===s?'active':''}">${s}${s==='Denials'?'<span>2</span>':''}</button>`).join('')}</nav><div class="period"><eds-select id="period" aria-label="Reporting period" size="sm"></eds-select></div></div>
 <section class="metrics" aria-label="Revenue cycle metrics">${this.metric('Total collections','$284,560','12.8%','vs. previous month','wallet2','28,33 42,30 52,34 65,19 78,25 90,12 106,16 122,3')}${this.metric('Outstanding receivables','$128,430','8.2%','vs. previous month','receipt','28,5 42,11 54,7 68,22 80,16 94,26 108,21 122,34',true)}${this.metric('Clean claim rate','96.4%','2.1 pts','vs. previous month','shield-check','28,32 42,30 54,21 67,25 80,12 94,17 108,9 122,4')}${this.metric('Days in A/R','32.6','4.2 days','vs. previous month','clock-history','28,6 42,14 54,10 68,22 80,19 94,30 108,26 122,35',true)}</section>
 <section class="analytics"><eds-card class="chart-card"><div class="panel-heading"><div><h2>Collections performance</h2><p>Payments received throughout the month</p></div><div class="segmented" aria-label="Chart display"><button class="selected" data-chart="daily">Daily</button><button data-chart="weekly">Weekly</button></div></div><div class="chart-summary"><strong id="chart-total">$284,560<span>.00</span></strong><span class="growth">${icon('arrow-up-right')} 12.8%</span><div class="legend"><span class="legend-dot orange"></span>Current month <span class="legend-dot gray"></span>Previous month</div></div><div id="chart"></div></eds-card>
 <eds-card class="payer-card"><div class="panel-heading"><div><h2>Revenue by payer</h2><p>Collected payments breakdown</p></div><eds-tooltip content="Based on this reporting period"><eds-icon name="info" size="sm"></eds-icon></eds-tooltip></div><div class="payer-content"><div class="donut" role="img" aria-label="Revenue by payer: Blue Cross Blue Shield 34%, Aetna 24%, UnitedHealthcare 20%, Medicare 14%, Cigna 8%"><div><small>Total collected</small><strong>$284.6k</strong><span>5 insurance payers</span></div></div><div class="payer-list">${[['Blue Cross Blue Shield','34%','#E87F24'],['Aetna','24%','#f5af75'],['UnitedHealthcare','20%','#284e49'],['Medicare','14%','#82aaa2'],['Cigna','8%','#d9e6e2']].map(([n,v,c])=>`<div><span class="legend-dot" style="background:${c}"></span><span>${n}</span><strong>${v}</strong></div>`).join('')}</div></div><div class="payer-footer">${icon('check-circle')} Insurance payments <strong>78%</strong><span></span>Patient payments <strong>22%</strong></div></eds-card></section>
 <section class="work-area"><eds-card class="accounts-card"><div class="panel-heading"><div class="title-line"><h2 id="table-title">Patient accounts</h2><eds-badge id="record-count" label="8 accounts" variant="neutral" pill></eds-badge></div><eds-button id="view-all" variant="tertiary" size="sm">View all accounts ${icon('arrow-up-right')}</eds-button></div><div class="table-controls"><eds-input id="search" icon="search" placeholder="Search patient, account, or claim…" aria-label="Search patient accounts"></eds-input><eds-select id="status-filter" aria-label="Filter by status"></eds-select></div><div class="table-scroll"><table><thead><tr><th>Patient</th><th id="payer-heading">Payer</th><th>Date of service</th><th class="numeric"><button id="sort-amount">Balance ${icon('arrow-down-up')}</button></th><th>Status</th><th></th></tr></thead><tbody id="account-rows"></tbody></table></div><div class="table-footer"><span id="table-summary"></span><eds-pagination id="pagination" page-size="5"></eds-pagination></div></eds-card>
 <div class="right-stack"><eds-card class="attention-card"><div class="panel-heading"><h2>Needs attention</h2><span class="attention-dot">3</span></div><button class="attention-item" data-nav="Denials"><span class="task-icon red">${icon('shield-exclamation')}</span><span><strong>2 claims need an appeal</strong><small>$3,860 in denied claims</small></span>${icon('chevron-right')}</button><button class="attention-item" data-nav="Collections"><span class="task-icon amber">${icon('clock-history')}</span><span><strong>2 overdue balances</strong><small>Follow up on $1,820</small></span>${icon('chevron-right')}</button><button class="attention-item" data-nav="Reimbursements"><span class="task-icon teal">${icon('arrow-left-right')}</span><span><strong>2 payments to reconcile</strong><small>Match payer remittances</small></span>${icon('chevron-right')}</button></eds-card>
 <eds-card class="target-card"><div class="panel-heading"><h2>Monthly collection goal</h2>${icon('bullseye')}</div><div class="target-value">$284,560 <span>/ $320,000</span></div><eds-progress-bar value="89" label="Monthly collection goal"></eds-progress-bar><div class="target-caption"><strong>89% achieved</strong><span>$35,440 to go</span></div></eds-card></div></section>
 <footer class="page-footer"><p class="page-footer-author"><span class="page-footer-kicker">Author</span><strong>Subrahmanyam Poluru</strong><a href="https://polurus.com" target="_blank" rel="noopener noreferrer">polurus.com</a></p><p class="page-footer-built">Built with <a href="https://www.npmjs.com/package/@poluru-labs/enterprise-design-system-wc" target="_blank" rel="noopener noreferrer">@poluru-labs/enterprise-design-system-wc</a></p></footer></main>
 <eds-modal id="payment-modal" heading="Record a patient payment"><div class="form-stack"><eds-alert variant="info">Payments are recorded in this demo session only.</eds-alert><eds-select id="payment-patient" label="Patient account" required></eds-select><eds-number-input id="payment-amount" label="Payment amount ($)" min="0.01" step="0.01" value="100"></eds-number-input><eds-select id="payment-method" label="Payment method"></eds-select><eds-input id="payment-ref" label="Reference number" placeholder="Optional receipt or transaction reference"></eds-input><eds-textarea id="payment-note" label="Notes" placeholder="Optional payment notes" rows="2"></eds-textarea><p id="payment-error" class="error" role="alert"></p></div><div slot="footer" class="modal-actions"><eds-button id="cancel-payment" variant="secondary">Cancel</eds-button><eds-button id="save-payment">Record payment</eds-button></div></eds-modal>
 <eds-drawer id="detail-drawer" heading="Patient account" side="right" size="md"><div id="detail-content"></div></eds-drawer>
 <eds-drawer id="notification-drawer" heading="Notifications" side="right" size="md"><eds-alert variant="warning" heading="Appeals require review">Two denied claims are waiting for documentation.</eds-alert><eds-divider></eds-divider><p>September collection goal is 89% complete.</p><p class="muted">All notifications are from the sample workspace.</p></eds-drawer>`;
 this.querySelectorAll('eds-card').forEach(async card=>{await card.updateComplete;const style=document.createElement('style');style.textContent='.header,.footer,.media{display:none}';card.shadowRoot.append(style);});
 this.bind();this.drawChart();this.renderRows();this.navigate(this.section);
 }
 metric(label,value,change,context,symbol,points,down=false){return `<eds-card class="metric"><div class="metric-label">${label}<span>${icon(symbol)}</span></div><div class="metric-value">${value}<svg viewBox="0 0 130 42" aria-hidden="true"><polyline points="${points}" fill="none" stroke="#72a18c" stroke-width="2"/></svg></div><div class="metric-foot"><span>${icon(down?'arrow-down-right':'arrow-up-right')} ${change}</span> ${context}</div></eds-card>`;}
 bind(){
 const $=s=>this.querySelector(s);const on=(s,fn)=>$(s).addEventListener('eds-click',fn);
 on('#nav-toggle',()=>{const open=!this.classList.contains('sidebar-open');this.classList.toggle('sidebar-open',open);$('.sidebar').hidden=!open;$('#nav-toggle').setAttribute('aria-expanded',String(open));$('#nav-toggle').setAttribute('accessible-label',open?'Hide sidebar':'Show sidebar');});
 this.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>this.navigate(b.dataset.nav)));
 $('#period').options=[{label:'September 2026',value:'September'},{label:'August 2026',value:'August'}];$('#period').value='September';$('#period').addEventListener('eds-change',()=>{this.drawChart();$('#chart-total').innerHTML=$('#period').value==='August'?'$252,269<span>.00</span>':'$284,560<span>.00</span>';});
 $('#status-filter').options=['All statuses','Pending','Overdue','Denied','Paid','Payment plan','In review'].map(s=>({label:s,value:s}));$('#status-filter').value=this.status;
 $('#status-filter').addEventListener('eds-change',e=>{this.status=e.detail.value;this.page=1;this.renderRows();});
 $('#search').addEventListener('eds-input',e=>{this.query=e.detail.value;this.page=1;this.renderRows();});
 $('#pagination').addEventListener('eds-change',e=>{this.page=e.detail.page;this.renderRows();});
 $('#sort-amount').addEventListener('click',()=>{this.sortAsc=!this.sortAsc;this.accounts.sort((a,b)=>this.sortAsc?a.amount-b.amount:b.amount-a.amount);this.renderRows();});
 this.querySelectorAll('[data-chart]').forEach(b=>b.addEventListener('click',()=>{this.querySelectorAll('[data-chart]').forEach(x=>x.classList.toggle('selected',x===b));this.weekly=b.dataset.chart==='weekly';this.drawChart();}));
 on('#view-all',()=>{this.navigate('Patient billing');$('#search').value='';this.query='';this.renderRows();});
 on('#notifications',()=>$('#notification-drawer').show());on('#payment',()=>this.openPayment());on('#cancel-payment',()=>$('#payment-modal').close());on('#save-payment',()=>this.savePayment());on('#export',()=>this.exportReport());
 $('#payment-method').options=['Credit card','Bank transfer','Check','Cash'].map(s=>({label:s,value:s}));$('#payment-method').value='Credit card';
 }
 navigate(section){this.section=section;this.page=1;this.status='All statuses';this.query='';this.querySelector('#search').value='';this.querySelector('#status-filter').value=this.status;history.replaceState(null,'',`#/${encodeURIComponent(section)}`);this.querySelector('#page-title').textContent=section==='Overview'?'Revenue cycle overview':section;this.querySelector('#page-subtitle').textContent=({Overview:'A clear view of your revenue. A better experience for your patients.','Patient billing':'Manage patient balances, statements, and payment history.',Claims:'Track claims from submission to payment.',Denials:'Review denied claims and prepare them for appeal.',Reimbursements:'Match payer remittances and reconcile received payments.',Collections:'Follow up on outstanding balances and payment plans.'})[section];this.querySelectorAll('[data-nav]').forEach(b=>{b.classList.toggle('active',b.dataset.nav===section);b.setAttribute('aria-current',b.dataset.nav===section?'page':'false');});this.querySelector('.analytics').hidden=section!=='Overview';this.querySelector('#table-title').textContent=section==='Overview'?'Patient accounts':section==='Patient billing'?'Patient accounts':section+' worklist';this.renderRows();document.title=`${section} · Covera`;}
 filtered(){return this.accounts.filter(a=>{const section=this.section==='Denials'?['Denied','In review'].includes(a.status):this.section==='Collections'?['Overdue','Payment plan'].includes(a.status):this.section==='Reimbursements'?['Paid','Pending'].includes(a.status):true;return section&&(this.status==='All statuses'||a.status===this.status)&&`${a.name} ${a.id} ${a.claim} ${a.payer}`.toLowerCase().includes(this.query.toLowerCase());});}
 renderRows(){const rows=this.filtered();const start=(this.page-1)*5;this.querySelector('#record-count').label=`${rows.length} accounts`;this.querySelector('#account-rows').innerHTML=rows.slice(start,start+5).map((a,i)=>`<tr><td><button class="patient-cell" data-account="${a.id}"><span class="initials color-${i%4}">${a.name.split(' ').map(n=>n[0]).join('')}</span><span><strong>${escape(a.name)}</strong><small>${a.id}</small></span></button></td><td>${escape(a.payer)}</td><td class="muted">${a.service}</td><td class="numeric balance">${money(a.amount)}</td><td><eds-badge variant="${variant(a.status)}" label="${a.status}" pill></eds-badge></td><td><eds-button data-account="${a.id}" variant="tertiary" icon="chevron-right" icon-only accessible-label="Open ${escape(a.name)} account" size="sm"></eds-button></td></tr>`).join('')||'<tr><td colspan="6" class="empty">No accounts match your search. Try another name or status.</td></tr>';this.querySelector('#table-summary').textContent=`Showing ${rows.length?start+1:0}–${Math.min(start+5,rows.length)} of ${rows.length} accounts`;this.querySelector('#pagination').total=rows.length;this.querySelector('#pagination').page=this.page;this.querySelectorAll('[data-account]').forEach(b=>b.addEventListener(b.tagName==='EDS-BUTTON'?'eds-click':'click',()=>this.openAccount(b.dataset.account)));}
 drawChart(){const prev=[82,90,79,110,97,101,118,115,137,113,127,121,143,151,144,167,158,176,170,198,185,205,192,209,222,212,229,221,230,238];let vals=[95,87,106,91,131,113,142,124,136,158,129,166,147,178,169,184,170,204,188,210,207,236,213,239,235,264,246,269,250,284];if(this.querySelector('#period').value==='August') vals=prev.map(n=>n*.92);const series=this.weekly?vals.filter((_,i)=>i%7===0):vals;const other=this.weekly?prev.filter((_,i)=>i%7===0):prev;const path=v=>v.map((n,i)=>`${50+i*(750/(v.length-1))},${192-n*.52}`).join(' ');this.querySelector('#chart').innerHTML=`<svg class="collections-chart" viewBox="0 0 830 235" role="img" aria-label="${this.weekly?'Weekly':'Daily'} collections trend, current month compared with previous month"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#E87F24" stop-opacity=".16"/><stop offset="100%" stop-color="#E87F24" stop-opacity="0"/></linearGradient></defs>${[0,1,2,3].map((n)=>`<line x1="50" y1="${30+n*53}" x2="805" y2="${30+n*53}" stroke="#edf0f2" stroke-dasharray="4 4"/><text x="0" y="${34+n*53}" fill="#90979f" font-size="12">$${30-n*10}k</text>`).join('')}<polygon points="50,192 ${path(series)} 800,192" fill="url(#area)"/><polyline points="${path(other)}" fill="none" stroke="#bdc7cb" stroke-width="2" stroke-dasharray="5 5" stroke-linejoin="round"/><polyline points="${path(series)}" fill="none" stroke="#E87F24" stroke-width="2.8" stroke-linejoin="round" stroke-linecap="round"/>${['Sep 01','Sep 05','Sep 10','Sep 15','Sep 20','Sep 25','Sep 30'].map((s,i)=>`<text x="${50+i*125}" y="223" text-anchor="${i===0?'start':i===6?'end':'middle'}" fill="#8b939c" font-size="12">${this.querySelector('#period').value==='August'?s.replace('Sep','Aug'):s}</text>`).join('')}</svg>`;}
 openPayment(id){const select=this.querySelector('#payment-patient');select.options=this.accounts.filter(a=>a.amount>0&&a.status!=='Paid').map(a=>({label:`${a.name} · ${money(a.amount)}`,value:a.id}));select.value=id||select.options[0]?.value;this.querySelector('#payment-error').textContent='';this.querySelector('#payment-modal').show();}
 savePayment(){const a=this.accounts.find(a=>a.id===this.querySelector('#payment-patient').value);const n=Number(this.querySelector('#payment-amount').value);if(!a||!Number.isFinite(n)||n<=0||n>a.amount){this.querySelector('#payment-error').textContent='Enter an amount greater than zero and no more than the outstanding balance.';return;}this.payments.push({patient:a.id,amount:money(n),method:this.querySelector('#payment-method').value,reference:this.querySelector('#payment-ref').value||'—',notes:this.querySelector('#payment-note').value||'',date:new Date().toLocaleDateString('en-US')});a.amount=Math.round((a.amount-n)*100)/100;a.status=a.amount===0?'Paid':'Payment plan';this.querySelector('#payment-modal').close();this.renderRows();showToast({message:`${money(n)} payment recorded for ${a.name}`,variant:'success'});}
 openAccount(id){const a=this.accounts.find(x=>x.id===id);const drawer=this.querySelector('#detail-drawer');drawer.heading=a.name;this.querySelector('#detail-content').innerHTML=`<div class="form-stack"><eds-badge variant="${variant(a.status)}" label="${a.status}"></eds-badge><div class="detail-balance"><small>Outstanding balance</small><strong>${money(a.amount)}</strong></div><eds-divider></eds-divider><dl><dt>Account</dt><dd>${a.id}</dd><dt>Claim</dt><dd>${a.claim}</dd><dt>Payer</dt><dd>${a.payer}</dd><dt>Service date</dt><dd>${a.service}</dd><dt>Assigned to</dt><dd>Priya Poluru</dd></dl><h2>Payment history</h2><eds-data-table id="payment-history" compact></eds-data-table><eds-accordion><eds-accordion-item heading="Claim history" open><p>Sep 12 · Claim submitted to ${a.payer}.</p><p>Sep 14 · Eligibility verified.</p><p>Sep 16 · ${a.status==='Denied'?'Denied: supporting documentation required.':'Account status updated.'}</p></eds-accordion-item></eds-accordion>${a.status==='Denied'?'<eds-alert variant="warning">Attach supporting documentation through your payer portal before submitting an appeal.</eds-alert><eds-button id="appeal">Mark appeal in review</eds-button>':a.status!=='Paid'?'<eds-button id="detail-payment">Record payment</eds-button>':'<eds-alert variant="success">Payment received and reconciled.</eds-alert>'}</div>`;const paymentTable=this.querySelector('#payment-history');paymentTable.columns=[{key:'date',label:'Date'},{key:'amount',label:'Amount'},{key:'method',label:'Method'},{key:'reference',label:'Reference'}];paymentTable.rows=this.payments.filter(p=>p.patient===id);if(a.received)paymentTable.rows=[{date:'Sep 14, 2026',amount:money(a.received),method:'Bank transfer',reference:'ERA-1085'},...paymentTable.rows];this.querySelector('#appeal')?.addEventListener('eds-click',()=>{a.status='In review';drawer.close();this.renderRows();showToast({message:`${a.claim} marked for appeal review`,variant:'success'});});this.querySelector('#detail-payment')?.addEventListener('eds-click',()=>{drawer.close();this.openPayment(id);});drawer.show();}
 exportReport(){const rows=[['Account','Patient','Payer','Service date','Balance','Status'],...this.filtered().map(a=>[a.id,a.name,a.payer,a.service,a.amount,a.status])];const csv=rows.map(r=>r.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download='covera-patient-accounts.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast({message:'Account report exported',variant:'success'});}
}
customElements.define('covera-app',CoveraApp);
