import { showToast } from '@poluru-labs/enterprise-design-system-wc';
import { scorecards, goals, people, alerts, reports } from '../data/index.js';
const icon = (name) => `<i class="bi bi-${name}" aria-hidden="true"></i>`;
const badge = (s) => `<eds-badge label="${s}" variant="${s === 'On track' ? 'success' : s === 'At risk' ? 'danger' : 'warning'}" pill></eds-badge>`;
const escape = (s) => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nav = [['overview','grid','Overview'],['scorecards','clipboard-data','Scorecards'],['goals','bullseye','Goals & targets'],['trends','graph-up-arrow','Analytics'],['teams','people','Team'],['reports','file-earmark-bar-graph','Reports']];
let cards = [...scorecards];
let filter = 'All scorecards';
let query = '';
let period = 'Q3';
const stored = window.localStorage.getItem('signal-cards');
try { if (stored) cards = JSON.parse(stored); } catch {}
const persist = () => window.localStorage.setItem('signal-cards', JSON.stringify(cards));
const link = (id, label, ico) => `<a href="#/${id}">${icon(ico)}<span>${label}</span></a>`;
class Dashboard extends HTMLElement {
 connectedCallback() {
  this.innerHTML = `<header class="topbar"><a class="logo" href="#/overview"><span class="logo-mark">${icon('bar-chart-fill')}</span>signal<span class="logo-dot">.</span></a><span class="header-divider"></span><span class="workspace">Clearline <span>Workspace</span></span><button class="mega-trigger" aria-expanded="false" aria-controls="mega">Explore ${icon('chevron-down')}</button><div class="header-search"><eds-search id="search" placeholder="Search your workspace" clearable></eds-search><eds-kbd keys="⌘K"></eds-kbd></div><eds-tooltip content="Notifications"><eds-button id="notifications" variant="tertiary" icon="bell" icon-only accessible-label="Notifications"></eds-button></eds-tooltip><span class="notification-dot"></span><span class="header-divider"></span><eds-avatar name="Mira Poluru" size="sm"></eds-avatar><div class="user-copy"><strong>Mira Poluru</strong><span>Workspace admin</span></div><eds-dropdown-menu id="profile"><button slot="trigger" class="icon-btn" aria-label="Profile menu">${icon('chevron-down')}</button><eds-menu-item value="settings" label="Workspace settings" icon="settings"></eds-menu-item><eds-menu-item value="teams" label="Your team" icon="user"></eds-menu-item></eds-dropdown-menu></header>
  <div class="mega" id="mega" hidden><div><small>WORKSPACE</small>${link('overview','Business overview','grid')}${link('scorecards','Performance scorecards','clipboard-data')}${link('goals','Goals & targets','bullseye')}</div><div><small>MEASURE & MANAGE</small>${link('trends','Analytics & trends','graph-up-arrow')}${link('teams','People & teams','people')}${link('reports','Report library','file-earmark-bar-graph')}</div><div class="mega-feature"><span class="eyebrow">YOUR QUARTER, IN FOCUS</span><h3>Big picture.<br>Every detail.</h3><p>One connected view of business performance.</p><a href="#/goals">Explore quarterly goals →</a></div></div>
  <aside class="sidebar"><button class="workspace-select" id="workspace-info"><span class="workspace-icon">C</span><span><strong>Clearline Holdings</strong><small>Enterprise workspace</small></span>${icon('chevron-expand')}</button><small class="nav-label">WORKSPACE</small><nav>${nav.map(([id,i,l])=>link(id,l,i)).join('')}<div class="nav-separator"></div>${link('alerts','Notifications','bell')}</nav><div class="sidebar-bottom"><div class="quarter-card"><div>${icon('pie-chart')}<strong>Q3 is in motion</strong><eds-badge label="2026" variant="neutral"></eds-badge></div><p>Make every milestone count.</p><eds-progress-bar value="86" label="Quarter elapsed"></eds-progress-bar><span>86% of quarter complete</span></div>${link('settings','Settings','gear')}${link('help','Help & resources','question-circle')}<div class="system-status"><span></span> All systems operational ${icon('arrow-up-right')}</div></div></aside>
  <main id="view" tabindex="-1"></main>
  <eds-modal id="create" heading="Create a scorecard" close-on-escape close-on-backdrop><div class="form-stack"><eds-input id="card-name" label="Scorecard name" placeholder="e.g. Customer experience" required></eds-input><eds-select id="card-owner" label="Owner"></eds-select><eds-textarea id="card-purpose" label="Focus" placeholder="What will this scorecard measure?"></eds-textarea><eds-slider id="card-health" label="Starting health" min="0" max="100" value="80" show-value></eds-slider><p id="form-error" role="alert"></p></div><div slot="footer" class="actions"><eds-button id="cancel-create" variant="secondary">Cancel</eds-button><eds-button id="save-create">Create scorecard</eds-button></div></eds-modal>
  <eds-drawer id="inbox" heading="Notifications" side="right"><div class="form-stack">${alerts.slice(0,3).map(a=>`<eds-alert variant="${a.severity==='Red'?'danger':'warning'}" title="${a.title}">${a.note}<p>${a.owner}</p></eds-alert>`).join('')}</div></eds-drawer>
  <eds-drawer id="detail" heading="Scorecard details" side="right"><div id="detail-body"></div></eds-drawer>`;
  this.querySelector('#card-owner').options = people.map(p=>({label:p.name,value:p.name}));
  this.querySelector('#card-owner').value = people[0].name;
  this.addEventListener('click', e => this.click(e));
  this.querySelector('#search').addEventListener('eds-input', e => {query=e.detail.value || '';this.render();});
  this.querySelector('#search').addEventListener('eds-clear', () => {query='';this.render();});
  this.querySelector('#search').addEventListener('eds-change', e => {query=e.detail.value || '';this.render();});
  this.querySelector('#profile').addEventListener('eds-select', e => location.hash=`#/${e.detail.value}`);
  this.onRoute = () => {this.closeMega();query='';this.querySelector('#search').value='';this.render();};
  window.addEventListener('hashchange',this.onRoute);
  this.onKey = e => {if(e.key==='Escape')this.closeMega();if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();this.querySelector('#search').shadowRoot.querySelector('input')?.focus();}};
  document.addEventListener('keydown',this.onKey);
  this.onOutside = e => {if(!e.composedPath().some(n=>n?.classList?.contains('mega')||n?.classList?.contains('mega-trigger')))this.closeMega();};
  document.addEventListener('click',this.onOutside);
  this.render();
 }
 disconnectedCallback(){window.removeEventListener('hashchange',this.onRoute);document.removeEventListener('keydown',this.onKey);document.removeEventListener('click',this.onOutside);}
 closeMega(){this.querySelector('#mega').hidden=true;this.querySelector('.mega-trigger').setAttribute('aria-expanded','false');}
 click(e){
  const b=e.target.closest('button,eds-button,a');if(!b)return;
  if(b.matches('.mega-trigger')){const m=this.querySelector('#mega');m.hidden=!m.hidden;b.setAttribute('aria-expanded',String(!m.hidden));}
  if(b.id==='notifications')this.querySelector('#inbox').show();
  if(b.id==='workspace-info')showToast({message:'Clearline Holdings · Enterprise workspace · 12 members',variant:'info'});
  if(b.hasAttribute('data-create'))this.querySelector('#create').show();
  if(b.id==='cancel-create')this.querySelector('#create').close();
  if(b.id==='save-create'){
   const name=this.querySelector('#card-name').value.trim();if(!name){this.querySelector('#form-error').textContent='Enter a scorecard name to continue.';return;}
   const health=Number(this.querySelector('#card-health').value);
   cards.push({id:`sc_${Date.now()}`,name,owner:this.querySelector('#card-owner').value,focus:this.querySelector('#card-purpose').value,health,status:health>=80?'On track':health>=70?'Watch':'At risk',kpis:0,updated:'23 Sep 2026'});persist();this.querySelector('#create').close();this.querySelector('#card-name').value='';this.querySelector('#form-error').textContent='';this.render();showToast({message:'Scorecard created',variant:'success'});
  }
  if(b.dataset.filter){filter=b.dataset.filter;this.render();}
  if(b.dataset.period){period=b.dataset.period;this.render();}
  if(b.dataset.detail){const c=cards.find(c=>c.id===b.dataset.detail);this.querySelector('#detail').heading=c.name;this.querySelector('#detail-body').innerHTML=`<div class="form-stack">${badge(c.status)}<h3>${escape(c.focus)}</h3><p>Owned by ${escape(c.owner)}</p><eds-progress-bar value="${c.health}" show-value label="Scorecard health"></eds-progress-bar><p>${c.kpis} tracked metrics · Updated ${c.updated}</p><eds-alert variant="info" title="Next check-in">Review progress with ${escape(c.owner)} on September 28.</eds-alert></div>`;this.querySelector('#detail').show();}
  if(b.hasAttribute('data-export')){const csv='Scorecard,Owner,Status,Health\n'+cards.map(c=>[c.name,c.owner,c.status,c.health].map(v=>'"'+String(v).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='signal-scorecards.csv';a.click();URL.revokeObjectURL(a.href);showToast({message:'Report exported',variant:'success'});}
  if(b.id==='save-settings'){window.localStorage.setItem('signal-digest',String(this.querySelector('#digest').checked));showToast({message:'Preferences saved',variant:'success'});}
 }
 render(){
  const route=location.hash.split('/')[1]||'overview';
  this.querySelectorAll('nav a').forEach(a=>{const active=a.hash===`#/${route}`;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
  const title=nav.find(n=>n[0]===route)?.[2]||({alerts:'Notifications',settings:'Settings',help:'Help & resources'}[route])||'Overview';
  document.title=`${title} · Signal`;
  this.querySelector('#view').innerHTML=`<div class="breadcrumb">Workspace ${icon('chevron-right')} <span>${title}</span><span class="demo-label">Demo workspace</span></div><section class="page-heading"><div><div class="eyebrow">YOUR BUSINESS, AT A GLANCE</div><h1>${route==='overview'?'Performance overview':title}<span class="heading-dot">.</span></h1><p>${route==='overview'?'Welcome back, Mira Poluru. Here’s how your business is moving.':'A shared view. Clear ownership. Measurable progress.'}</p></div><div class="actions"><eds-button variant="secondary" icon="download" data-export>Export report</eds-button><eds-button icon="plus" data-create>New scorecard</eds-button></div></section>${query?`<eds-alert variant="info" title="Search results">Showing scorecards matching “${escape(query)}”.</eds-alert>${this.table()}`:this.page(route)}<footer class="page-footer"><span>Created by <a href="https://polurus.com" target="_blank" rel="noopener noreferrer">Subrahmanyam Poluru</a></span><span>Built with <a href="https://www.npmjs.com/package/@poluru-labs/enterprise-design-system-wc" target="_blank" rel="noopener noreferrer">@poluru-labs/enterprise-design-system-wc</a></span></footer>`;
 }
 page(route){
  if(route==='overview')return this.overview();
  if(route==='scorecards')return this.table();
  if(route==='trends')return `<div class="wide-chart">${this.chart()}</div>`;
  if(route==='goals')return `<div class="goal-grid">${goals.map(g=>`<eds-card padded><div class="card-top">${badge(g.status)}<span>${g.target}</span></div><h3>${g.name}</h3><p>${g.owner} · ${g.scorecard}</p><eds-progress-bar value="${g.progress}" label="Goal progress" show-value></eds-progress-bar></eds-card>`).join('')}</div>`;
  if(route==='teams')return `<div class="goal-grid">${people.map(p=>`<eds-card padded><eds-avatar name="${p.name}"></eds-avatar><h3>${p.name}</h3><p>${p.role}</p><eds-badge variant="brand" label="${p.squad}"></eds-badge><eds-progress-bar value="${p.score}" label="Team health" show-value></eds-progress-bar></eds-card>`).join('')}</div>`;
  if(route==='reports')return `<section class="panel"><div class="panel-heading"><h2>Report library</h2><eds-badge label="6 reports" variant="neutral"></eds-badge></div>${reports.map(r=>`<div class="report-row"><span class="activity-icon">${icon('file-earmark-text')}</span><div><strong>${r.name}</strong><p>${r.owner} · ${r.updated}</p></div><eds-badge label="${r.format}" variant="neutral"></eds-badge><eds-button variant="secondary" data-export>Export CSV</eds-button></div>`).join('')}</section>`;
  if(route==='alerts')return `<div class="form-stack">${alerts.map(a=>`<eds-alert variant="${a.severity==='Red'?'danger':a.severity==='Amber'?'warning':'info'}" title="${a.title}">${a.note} — ${a.owner}</eds-alert>`).join('')}</div>`;
  if(route==='settings')return `<section class="panel settings"><h2>Workspace preferences</h2><p>Personalize your Clearline experience on this device.</p><eds-switch id="digest" label="Weekly performance digest" ${window.localStorage.getItem('signal-digest')==='true'?'checked':''}></eds-switch><eds-divider></eds-divider><eds-button id="save-settings">Save preferences</eds-button></section>`;
  return `<section class="panel settings"><h2>A little clarity goes a long way.</h2><eds-accordion><eds-accordion-item heading="How do scorecards work?">Scorecards group metrics under a single owner. Open a scorecard to review its health and focus.</eds-accordion-item><eds-accordion-item heading="How do I export my data?">Select Export report to download the workspace scorecards as a CSV file.</eds-accordion-item><eds-accordion-item heading="Where is my data saved?">This is a demo workspace. New scorecards and preferences are saved in this browser.</eds-accordion-item></eds-accordion></section>`;
 }
 overview(){return `<div class="context-bar"><div><span class="live-status"><span></span> Live overview</span><span class="context-divider"></span><span>All departments ${icon('chevron-down')}</span></div><div>${icon('calendar3')} Jul 1 – Sep 30, 2026 <eds-badge label="Q3 2026" variant="brand"></eds-badge></div></div><section class="stats-grid">${[
 ['Total revenue','$18.4M','+7.6%','vs. $17.1M target','currency-dollar',[35,42,39,51,46,63,61,78,73,88]],
 ['Net revenue retention','118%','+4 pts','vs. previous quarter','arrow-repeat',[30,43,38,54,52,61,58,76,73,84]],
 ['Gross margin','71.2%','+1.2 pts','vs. 70% target','pie-chart',[34,40,42,39,56,52,67,61,74,82]],
 ['Customer satisfaction','4.7','+0.2','out of 5 · last 30 days','emoji-smile',[44,42,50,48,61,60,66,70,72,84]]
 ].map(([l,v,t,h,i,p])=>`<div class="stat-card"><div class="stat-label">${l}<span>${icon(i)}</span></div><div class="stat-value">${v}<span class="trend">${icon('arrow-up-right')} ${t}</span></div><div class="stat-bottom"><span>${h}</span><svg viewBox="0 0 100 36" aria-hidden="true"><polyline points="${p.map((n,j)=>`${j*11},${40-n*.36}`).join(' ')}" fill="none" stroke="#258a83" stroke-width="1.8"/></svg></div></div>`).join('')}</section><div class="analytics-grid">${this.chart()}${this.health()}</div><div class="lower-grid">${this.table(true)}<section class="panel activity"><div class="panel-heading"><h2>Workspace activity</h2><span class="live-dot"></span></div><p class="panel-subtitle">The latest from your team</p>${[['Arjun Poluru','updated the Finance scorecard','12 min ago','clipboard-data'],['Kavya Poluru','reached 94% of the retention goal','38 min ago','bullseye'],['Priya Poluru','published the customer voice report','1 hour ago','file-earmark-text']].map(([n,a,t,i])=>`<div class="activity-row"><span class="activity-icon">${icon(i)}</span><div><strong>${n}</strong><p>${a}</p><small>${t}</small></div></div>`).join('')}<a class="text-link activity-link" href="#/teams">Meet your team ${icon('arrow-right')}</a><div class="review-callout"><span>${icon('calendar-event')} NEXT ON YOUR CALENDAR</span><h3>Quarterly business review</h3><p>Sep 28 · 10:00 AM · Mira Poluru</p><a href="#/goals">Review quarterly goals ${icon('arrow-up-right')}</a></div></section></div>`;}
 chart(){const q=period==='Q3';return `<section class="panel revenue-panel"><div class="panel-heading"><div><h2>Revenue performance</h2><p>Steady growth. A strong finish in sight.</p></div><div class="segmented"><button data-period="Q2" class="${!q?'selected':''}">Q2</button><button data-period="Q3" class="${q?'selected':''}">Q3</button></div></div><div class="chart-summary"><strong>${q?'$18.4M':'$16.1M'}</strong><span class="trend">${icon('arrow-up-right')} ${q?'7.6':'5.2'}%</span><div class="chart-legend"><span><b></b> Revenue</span><span><b class="target"></b> Target</span></div></div><div class="chart-wrap"><svg viewBox="0 0 740 220" role="img" aria-label="${period} revenue rises from ${q?'12.8 to 18.4':'11.2 to 16.1'} million dollars, above target"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="#006199" stop-opacity=".17"/><stop offset="100%" stop-color="#006199" stop-opacity="0"/></linearGradient></defs>${[25,70,115,160].map((y,i)=>`<line x1="46" y1="${y}" x2="720" y2="${y}" stroke="#e8edf2" stroke-dasharray="3 5"/><text x="0" y="${y+4}">$${20-i*4}M</text>`).join('')}<path d="M48 151 C80 150 90 144 112 142 S158 151 183 124 S235 137 260 108 S312 112 339 94 S387 108 415 82 S467 97 492 61 S545 69 571 43 S620 53 650 26 S695 40 718 ${q?'12':'30'} L718 179 L48 179Z" fill="url(#area)"/><path d="M48 161 C140 154 180 142 260 125 S400 113 492 83 S626 65 718 43" fill="none" stroke="#a8bac9" stroke-width="2" stroke-dasharray="5 6"/><path d="M48 151 C80 150 90 144 112 142 S158 151 183 124 S235 137 260 108 S312 112 339 94 S387 108 415 82 S467 97 492 61 S545 69 571 43 S620 53 650 26 S695 40 718 ${q?'12':'30'}" fill="none" stroke="#006199" stroke-width="3" stroke-linecap="round"/><circle cx="718" cy="${q?'12':'30'}" r="5" fill="#006199" stroke="white" stroke-width="3"/>${(q?['Jul 01','Jul 15','Aug 01','Aug 15','Sep 01','Sep 15','Sep 30']:['Apr 01','Apr 15','May 01','May 15','Jun 01','Jun 15','Jun 30']).map((t,i)=>`<text x="${47+i*108}" y="208">${t}</text>`).join('')}</svg></div><div class="chart-footer"><span>${icon('check-circle-fill')} Revenue is ${q?'$1.3M':'$0.8M'} ahead of plan</span><a href="#/trends">Explore analytics ${icon('arrow-up-right')}</a></div></section>`;}
 health(){const avg=Math.round(cards.reduce((s,c)=>s+c.health,0)/cards.length);return `<section class="panel health-panel"><div class="panel-heading"><h2>Portfolio health</h2><eds-tooltip content="Average health across all scorecards">${icon('info-circle')}</eds-tooltip></div><p class="panel-subtitle">A pulse on your business</p><div class="donut" style="--track:${cards.filter(c=>c.status==='On track').length/cards.length*100}%;--watch:${cards.filter(c=>c.status!=='At risk').length/cards.length*100}%"><div><strong>${avg}<span>%</span></strong><small>Overall health</small></div></div><div class="health-legend">${[['On track','good'],['Watch','watch'],['At risk','risk']].map(([s,c])=>`<div><span class="status-dot ${c}"></span><span>${s}</span><strong>${cards.filter(x=>x.status===s).length}</strong></div>`).join('')}</div><a class="text-link health-link" href="#/scorecards">View all scorecards ${icon('arrow-right')}</a></section>`;}
 table(compact=false){const rows=cards.filter(c=>(filter==='All scorecards'||c.status===filter)&&`${c.name} ${c.owner} ${c.focus}`.toLowerCase().includes(query.toLowerCase()));return `<section class="panel scorecards-panel"><div class="panel-heading"><div><h2>Department scorecards <span class="count">${cards.length}</span></h2><p>Clear ownership. Shared momentum.</p></div>${compact?'<a class="text-link" href="#/scorecards">View all →</a>':'<eds-button variant="secondary" data-create icon="plus">Add scorecard</eds-button>'}</div><div class="filter-tabs" role="group" aria-label="Filter scorecards">${['All scorecards','On track','Watch','At risk'].map(s=>`<button data-filter="${s}" aria-pressed="${filter===s}" class="${filter===s?'selected':''}">${s}</button>`).join('')}</div><div class="table-scroll"><table><thead><tr><th>Department</th><th>Owner</th><th>Health</th><th>Status</th><th><span class="visually-hidden">Details</span></th></tr></thead><tbody>${rows.slice(0,compact?5:rows.length).map((c,i)=>`<tr><td><button class="department" data-detail="${c.id}"><span class="department-icon tone-${i%4}">${icon(['bank','graph-up-arrow','box','people','gear'][i%5])}</span><span>${escape(c.name)}<small>${c.kpis} metrics</small></span></button></td><td><div class="owner"><eds-avatar name="${escape(c.owner)}" size="xs"></eds-avatar><span>${escape(c.owner)}</span></div></td><td><div class="table-health"><span>${c.health}%</span><eds-progress-bar value="${c.health}" label="${escape(c.name)} health"></eds-progress-bar></div></td><td>${badge(c.status)}</td><td><button class="icon-btn" data-detail="${c.id}" aria-label="Open ${escape(c.name)}">${icon('arrow-up-right')}</button></td></tr>`).join('')}</tbody></table>${!rows.length?'<eds-empty-state heading="No scorecards found" description="Try a different search or status filter." icon="search"></eds-empty-state>':''}</div><div class="table-footer"><span>Showing ${Math.min(rows.length,compact?5:rows.length)} of ${rows.length} scorecards</span><span>Updated just now ${icon('arrow-clockwise')}</span></div></section>`;}
}
customElements.define('signal-dashboard',Dashboard);
