const icon=(name)=>`<i class="bi bi-${name}" aria-hidden="true"></i>`;
const sites=[
 {name:'Suncrest Solar Park',location:'Phoenix, Arizona',type:'Solar',icon:'sun',capacity:120,production:98.4,status:'Operational',availability:99.8,owner:'Arjun Poluru'},
 {name:'Westhaven Wind Farm',location:'Abilene, Texas',type:'Wind',icon:'wind',capacity:180,production:142.6,status:'Operational',availability:99.5,owner:'Maya Poluru'},
 {name:'Clearwater Hydro',location:'Bend, Oregon',type:'Hydro',icon:'droplet',capacity:85,production:72.8,status:'Operational',availability:99.9,owner:'Rohan Poluru'},
 {name:'Mesa Valley Solar',location:'Tucson, Arizona',type:'Solar',icon:'sun',capacity:95,production:64.2,status:'Maintenance',availability:96.4,owner:'Neha Poluru'},
 {name:'Northshore Wind',location:'Amarillo, Texas',type:'Wind',icon:'wind',capacity:150,production:108.5,status:'Operational',availability:99.6,owner:'Kiran Poluru'},
 {name:'Redwood Battery Storage',location:'Fresno, California',type:'Storage',icon:'battery-charging',capacity:60,production:38.1,status:'Outage',availability:94.2,owner:'Isha Poluru'}
];
let state={view:'Overview',type:'all',query:'',period:'week',page:1};
let workOrders=JSON.parse(window.localStorage.getItem('terra-work-orders')||'null')||[
 {title:'Inverter inspection',site:'Mesa Valley Solar',owner:'Neha Poluru',date:'Today, 10:30 AM',priority:'High'},
 {title:'Turbine lubrication',site:'Westhaven Wind Farm',owner:'Maya Poluru',date:'Today, 2:00 PM',priority:'Medium'},
 {title:'Annual safety audit',site:'Clearwater Hydro',owner:'Rohan Poluru',date:'Sep 18, 9:00 AM',priority:'Low'}];
const nav=['Overview','Sites','Production','Outages','Maintenance','Consumption','Sustainability'];
const badge=(text,variant='success')=>`<eds-badge label="${text}" variant="${variant}" soft pill></eds-badge>`;
const panel=(content,cls='')=>`<eds-card class="panel ${cls}">${content}</eds-card>`;
const sectionHead=(title,sub,action='')=>`<div class="panel-heading"><div><h2>${title}</h2>${sub?`<p>${sub}</p>`:''}</div>${action}</div>`;
const link=(text,view)=>`<button class="text-button" data-view="${view}">${text} ${icon('arrow-right')}</button>`;
function spark(color,seed=0){return `<svg class="spark" viewBox="0 0 112 40" aria-hidden="true"><path d="M1 ${30-seed} L12 29 L22 33 L33 21 L43 25 L54 17 L64 20 L75 8 L85 14 L97 6 L111 3" fill="none" stroke="${color}" stroke-width="2.2" stroke-linejoin="round"/></svg>`;}
function stats(){return `<div class="stats">${[
 ['Total production','bolt','1,284.6','MWh','12.8%','vs. previous week','#4e61d3'],
 ['Energy consumption','plug','846.2','MWh','4.2%','vs. previous week','#42a997'],
 ['Fleet availability','activity','98.6','%','0.8%','above 97.5% target','#6e86c8'],
 ['Carbon avoided','leaf','428.5','tCO₂','18.6%','vs. previous week','#42976b']
 ].map((s,i)=>panel(`<div class="stat-top"><span>${s[0]}</span><span class="metric-icon tone-${i}">${icon(s[1]==='bolt'?'lightning-charge':s[1]==='leaf'?'leaf':s[1])}</span></div><div class="metric-value">${s[2]} <small>${s[3]}</small></div><div class="stat-bottom"><span><b>${icon(i===1?'arrow-down-right':'arrow-up-right')} ${s[4]}</b><small>${s[5]}</small></span>${spark(s[6],i*2)}</div>`,'metric')).join('')}</div>`;}
function chart(){let p=state.period;let values=p==='week'?[74,82,71,97,89,109,115,105,123,117,104,130,119,136,125,141,130,139,119,131,148,139,163,154,172,156,166,160]:p==='month'?[63,74,82,65,99,90,115,106,122,115,136,118,143,130,162,145,151,163,149,167,153,182,176,163,170,188,177,184]:[60,67,65,63,82,98,109,140,155,167,174,187,190,186,178,163,151,134,109,95,83,70,65,61,58,57,56,55];let points=values.map((v,i)=>`${55+i*25},${240-v}`).join(' ');let cons=values.map((v,i)=>`${55+i*25},${250-v*.68+(i%3)*6}`).join(' ');return `<svg class="production-chart" viewBox="0 0 770 290" role="img" aria-label="${p} production and consumption trend in MWh"><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#4e61d3" stop-opacity=".17"/><stop offset="1" stop-color="#4e61d3" stop-opacity="0"/></linearGradient></defs>${[0,1,2,3,4].map((v)=>`<text x="5" y="${44+v*48}" fill="#8b91a2" font-size="12">${200-v*50}</text><line x1="48" y1="${40+v*48}" x2="742" y2="${40+v*48}" stroke="#edf0f5" stroke-dasharray="4 5"/>`).join('')}<polygon points="55,240 ${points} 730,240" fill="url(#area)"/><polyline points="${points}" fill="none" stroke="#4e61d3" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><polyline points="${cons}" fill="none" stroke="#46aa9a" stroke-width="2.5" stroke-dasharray="6 5" stroke-linecap="round"/>${(p==='week'?['Mon, 14','Tue, 15','Wed, 16','Thu, 17','Fri, 18','Sat, 19','Sun, 20']:p==='month'?['Sep 1','Sep 5','Sep 10','Sep 15','Sep 20','Sep 25','Sep 30']:['00:00','04:00','08:00','12:00','16:00','20:00','23:00']).map((t,i)=>`<text x="${55+i*112}" y="273" fill="#8b91a2" font-size="12" text-anchor="middle">${t}</text>`).join('')}</svg>`;}
function production(){return panel(`${sectionHead('Production & consumption','Energy performance across your portfolio',`<eds-segmented-control id="chart-period" size="sm" value="${state.period}"></eds-segmented-control>`)}<div class="chart-summary"><div><strong>1,284.6 <small>MWh</small></strong><span class="positive">${icon('arrow-up-right')} 12.8%</span></div><div class="legend"><span><b style="background:#4e61d3"></b>Production</span><span><b style="background:#46aa9a"></b>Consumption</span></div></div><div id="chart">${chart()}</div><div class="chart-note">${icon('info-circle')} Production exceeded consumption by <strong>438.4 MWh</strong> this week.</div>`,'production');}
function mix(){return panel(`${sectionHead('Energy mix','Production by source',icon('pie-chart'))}<div class="donut-wrap"><div class="donut"><div><span>Total production</span><strong>1,284.6</strong><small>MWh</small></div></div></div><div class="mix-legend">${[['Solar','sun','48.2','619.2','#4e61d3'],['Wind','wind','32.6','418.8','#8898ed'],['Hydro','droplet','15.4','197.8','#54b8a4'],['Storage','battery-charging','3.8','48.8','#d6e8e2']].map(s=>`<div><span><b style="background:${s[4]}"></b>${s[0]}</span><strong>${s[2]}%</strong><small>${s[3]} MWh</small></div>`).join('')}</div>`,'mix');}
function siteRows(){let filtered=sites.filter(s=>(state.type==='all'||s.type===state.type)&&`${s.name} ${s.owner} ${s.location}`.toLowerCase().includes(state.query));let shown=state.view==='Overview'?filtered.slice(0,4):filtered;return shown.length?shown.map(s=>`<tr><td><button class="site-link" data-site="${s.name}"><span class="site-icon ${s.type.toLowerCase()}">${icon(s.icon)}</span><span><strong>${s.name}</strong><small>${s.location}</small></span></button></td><td>${badge(s.type,'neutral')}</td><td>${s.capacity} <span class="muted">MW</span></td><td><strong>${s.production}</strong> <span class="muted">MWh</span></td><td><div class="availability"><span>${s.availability}%</span><eds-progress-bar value="${s.availability}"></eds-progress-bar></div></td><td><eds-status label="${s.status}" variant="${s.status==='Operational'?'success':s.status==='Maintenance'?'warning':'danger'}"></eds-status></td><td><button class="row-arrow" data-site="${s.name}" aria-label="View ${s.name}">${icon('arrow-up-right')}</button></td></tr>`).join(''):`<tr><td colspan="7"><eds-empty-state heading="No matching sites" description="Try a different name or energy source." icon="search"></eds-empty-state></td></tr>`;}
function siteTable(){return panel(`${sectionHead('Site performance',`<span class="inline-count">6 sites</span> A closer look at your energy assets`,link('View all sites','Sites'))}<div class="table-filters"><eds-search id="site-search" placeholder="Search sites or owners…" clearable size="sm"></eds-search><eds-select id="type-filter" size="sm" aria-label="Energy source"></eds-select></div><div class="table-scroll"><table><thead><tr><th>Site name</th><th>Source</th><th>Capacity</th><th>Production ${icon('arrow-down')}</th><th>Availability</th><th>Status</th><th></th></tr></thead><tbody id="site-rows">${siteRows()}</tbody></table></div><div class="table-footer"><span>Showing ${state.view==='Overview'?'4 of ':''}6 sites <span class="muted">· Sample portfolio</span></span><span>${icon('arrow-repeat')} Updated Sep 16, 2026 · 09:41 AM</span></div>`,'site-panel');}
function maintenance(){return panel(`${sectionHead('Upcoming maintenance','Keep your assets running at their best',link('View schedule','Maintenance'))}<div class="work-list">${workOrders.slice(0,state.view==='Overview'?3:20).map((w,i)=>`<button class="work-item" data-work="${i}"><span class="work-icon">${icon('tools')}</span><span class="work-copy"><strong>${escapeHtml(w.title)}</strong><small>${escapeHtml(w.site)} <span>·</span> ${escapeHtml(w.date)}</small></span>${badge(w.priority,w.priority==='High'?'danger':w.priority==='Medium'?'warning':'neutral')}<eds-avatar name="${escapeHtml(w.owner)}" size="sm"></eds-avatar></button>`).join('')}</div><div class="panel-bottom">${icon('calendar3')} <span>${workOrders.length} planned tasks</span><button class="text-button" data-action="new-work">Schedule maintenance ${icon('plus')}</button></div>`,'maintenance');}
function sustainability(){return panel(`${sectionHead('A cleaner energy future','Your sustainability impact this week',badge('On track'))}<div class="impact"><span class="impact-icon">${icon('leaf')}</span><div><strong>428.5 <small>tCO₂</small></strong><p>Carbon emissions avoided</p></div></div><div class="goal-label"><span>Monthly carbon reduction target</span><strong>76%</strong></div><eds-progress-bar value="76" label="Monthly target progress"></eds-progress-bar><div class="impact-footer"><span>1,520 / 2,000 tCO₂</span>${link('Sustainability','Sustainability')}</div>`,'sustainability');}
function outage(){return panel(`${sectionHead('Active outages','Prioritized incidents requiring attention',badge('1 active','danger'))}<eds-alert variant="warning" title="Redwood Battery Storage" message="PCS communication loss · 21.9 MW affected · Since 08:15 AM"></eds-alert><div class="detail-grid"><div><small>Incident owner</small><strong>Isha Poluru</strong></div><div><small>Estimated restoration</small><strong>Today, 12:30 PM</strong></div></div><eds-button data-action="incident" variant="secondary">View incident timeline</eds-button>`);}
function escapeHtml(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
const app=document.querySelector('#app');
app.innerHTML=`<header class="topbar"><a href="#/overview" class="brand"><span class="brand-symbol">${icon('lightning-charge-fill')}</span><span>terra<span class="brand-light">energy</span><small>ENERGY OPERATIONS</small></span></a><div class="workspace"><span class="divider-vertical"></span><span>Enterprise workspace</span><eds-badge label="PRO" variant="neutral" soft></eds-badge></div><div class="header-actions"><button class="global-search" data-action="search">${icon('search')} <span>Search anything…</span><eds-kbd keys="⌘ K"></eds-kbd></button><eds-tooltip content="Notifications"><button class="icon-button notification" data-action="notifications" aria-label="Notifications">${icon('bell')}<b></b></button></eds-tooltip><span class="divider-vertical"></span><button class="profile" data-action="profile"><eds-avatar name="Aditya Poluru" size="sm"></eds-avatar><span><strong>Aditya Poluru</strong><small>Operations manager</small></span>${icon('chevron-down')}</button></div></header>
<nav class="main-nav" aria-label="Main navigation"><div class="nav-links">${nav.map((n,i)=>`<a href="#/${n.toLowerCase()}" data-nav="${n}">${icon(['grid-1x2','geo-alt','lightning-charge','exclamation-triangle','tools','plug','leaf'][i])}${n}${n==='Outages'?'<span class="nav-count">1</span>':''}</a>`).join('')}</div><button id="mega-toggle" aria-expanded="false" aria-controls="mega-menu">${icon('grid-3x3-gap')} All modules ${icon('chevron-down')}</button></nav>
<div id="mega-menu" class="mega-menu" hidden><div><h3>OPERATIONS</h3>${nav.slice(1,5).map(n=>`<button data-view="${n}">${n} ${icon('arrow-up-right')}</button>`).join('')}</div><div><h3>PERFORMANCE & IMPACT</h3>${['Overview','Consumption','Sustainability'].map(n=>`<button data-view="${n}">${n} ${icon('arrow-up-right')}</button>`).join('')}</div><div class="mega-highlight"><span>${icon('lightning-charge')} TERRA WORKSPACE</span><h3>Your energy. One clear view.</h3><p>Monitor assets, manage maintenance, and measure your portfolio’s impact.</p><eds-button data-action="export" variant="secondary">Export portfolio</eds-button></div></div>
<main id="view"></main><footer class="page-footer"><span><span class="footer-mark">${icon('lightning-charge-fill')}</span> Terra Energy <span>·</span> Enterprise operations</span><span>Sample workspace <span>·</span> All times CDT <span>·</span> <span class="system-status">${icon('check-circle')} Workspace ready</span></span></footer>
<eds-drawer id="detail-drawer" heading="Site details" size="md"><div id="drawer-content"></div></eds-drawer>
<eds-modal id="work-modal" heading="Schedule maintenance" close-on-backdrop close-on-escape><div class="form-stack"><eds-input id="work-title" label="Task name" placeholder="e.g. Quarterly inverter inspection" required></eds-input><eds-select id="work-site" label="Site"></eds-select><eds-select id="work-owner" label="Assign to"></eds-select><eds-date-picker id="work-date" label="Scheduled date" value="2026-09-18"></eds-date-picker><eds-radio-group id="work-priority" label="Priority" value="Medium" orientation="horizontal"><eds-radio name="priority" label="Low" value="Low"></eds-radio><eds-radio name="priority" label="Medium" value="Medium"></eds-radio><eds-radio name="priority" label="High" value="High"></eds-radio></eds-radio-group><eds-textarea id="work-notes" label="Notes" placeholder="Inspection scope and access instructions" rows="3"></eds-textarea><p id="form-error" role="alert"></p></div><div slot="footer" class="modal-footer"><eds-button data-action="cancel-work" variant="secondary">Cancel</eds-button><eds-button data-action="save-work">Schedule task</eds-button></div></eds-modal>
<eds-modal id="search-modal" heading="Search your workspace" close-on-backdrop close-on-escape><eds-search id="global-input" placeholder="Search sites, people, or modules" clearable></eds-search><div id="search-results"></div></eds-modal><eds-toast id="toast" duration="4000" variant="success"></eds-toast>`;
function render(){document.title=`${state.view} · Terra Energy`;document.querySelectorAll('[data-nav]').forEach(el=>{el.classList.toggle('active',el.dataset.nav===state.view);el.setAttribute('aria-current',el.dataset.nav===state.view?'page':'false');});document.querySelector('#view').innerHTML=`<div class="breadcrumbs">Workspace ${icon('chevron-right')} <span>${state.view}</span></div><div class="page-heading"><div><div class="eyebrow">YOUR ENERGY, CONNECTED</div><h1>${state.view==='Overview'?'Portfolio overview':state.view==='Sites'?'Your energy sites':state.view}</h1><p>${state.view==='Overview'?'A clear picture of your energy operations. Every site, every megawatt.':({Sites:'Monitor performance and health across your energy portfolio.',Production:'Track generation and balance supply across energy sources.',Outages:'Coordinate response and bring your assets back online.',Maintenance:'Plan, assign, and track asset maintenance.',Consumption:'Understand demand and manage your energy balance.',Sustainability:'Measure progress toward a lower-carbon portfolio.'}[state.view])}</p></div><div class="page-actions"><span class="snapshot">${icon('clock')} Sep 16, 2026</span><eds-button data-action="export" variant="secondary" icon="download">Export report</eds-button><eds-button data-action="new-work" icon="plus">Schedule task</eds-button></div></div>${state.view==='Overview'?`<div class="portfolio-strip"><div>${icon('buildings')}<strong>All sites</strong><span class="strip-count">6</span><span class="strip-divider"></span><span><b class="dot green"></b>4 operational</span><span><b class="dot amber"></b>1 in maintenance</span><span><b class="dot red"></b>1 outage</span></div><span class="sample-data">${icon('database')} Sample data <eds-tooltip content="Illustrative portfolio data for September 2026"><eds-icon name="info" size="sm"></eds-icon></eds-tooltip></span></div>${stats()}<div class="main-grid">${production()}${mix()}</div>${siteTable()}<div class="bottom-grid">${maintenance()}${sustainability()}</div>`:state.view==='Sites'?siteTable():state.view==='Maintenance'?maintenance():state.view==='Outages'?outage():state.view==='Sustainability'?`${stats()}<div class="bottom-grid">${sustainability()}${mix()}</div>`:`${stats()}<div class="main-grid">${production()}${mix()}</div>`}`;
 document.querySelectorAll('eds-card').forEach(el=>el.padded=false);
 let period=document.querySelector('#chart-period');if(period){period.options=[{label:'24 hours',value:'day'},{label:'7 days',value:'week'},{label:'30 days',value:'month'}];period.addEventListener('eds-change',e=>{state.period=e.detail.value;document.querySelector('#chart').innerHTML=chart();});}
 let filter=document.querySelector('#type-filter');if(filter){filter.options=[{label:'All sources',value:'all'},...['Solar','Wind','Hydro','Storage'].map(s=>({label:s,value:s}))];filter.value=state.type;filter.addEventListener('eds-change',e=>{state.type=e.detail.value;document.querySelector('#site-rows').innerHTML=siteRows();});}
 let search=document.querySelector('#site-search');if(search){search.value=state.query;search.addEventListener('eds-input',e=>{state.query=e.detail.value.toLowerCase();document.querySelector('#site-rows').innerHTML=siteRows();});search.addEventListener('eds-change',e=>{state.query=e.detail.value.toLowerCase();document.querySelector('#site-rows').innerHTML=siteRows();});}
}
function navigate(view){location.hash='/'+view.toLowerCase();closeMega();}
function closeMega(){document.querySelector('#mega-menu').hidden=true;document.querySelector('#mega-toggle').setAttribute('aria-expanded','false');}
function toast(message){const t=document.querySelector('#toast');t.message=message;t.open=true;}
function drawer(heading,content){const el=document.querySelector('#detail-drawer');el.heading=heading;document.querySelector('#drawer-content').innerHTML=content;el.show();}
function exportReport(){const rows=[['Site','Source','Capacity MW','Production MWh','Availability %','Status','Owner'],...sites.filter(s=>state.type==='all'||s.type===state.type).map(s=>[s.name,s.type,s.capacity,s.production,s.availability,s.status,s.owner])];let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([rows.map(r=>r.map(c=>'"'+String(c).replaceAll('"','""')+'"').join(',')).join('\r\n')],{type:'text/csv'}));a.download='terra-energy-portfolio-2026-09-16.csv';a.click();URL.revokeObjectURL(a.href);toast('Portfolio report exported.');}
function searchResults(query=''){const results=[...nav.map(n=>({name:n,view:n,sub:'Workspace module'})),...sites.map(s=>({name:s.name,site:s.name,sub:s.owner+' · '+s.type}))].filter(s=>(s.name+' '+s.sub).toLowerCase().includes(query.toLowerCase()));document.querySelector('#search-results').innerHTML=results.length?results.map(s=>`<button class="search-result" data-${s.site?'site':'view'}="${s.site||s.view}"><strong>${s.name}</strong><small>${s.sub}</small>${icon('arrow-up-right')}</button>`).join(''):'<eds-empty-state heading="No results" description="Try a site name or owner."></eds-empty-state>';}
app.addEventListener('click',e=>{let el=e.target.closest('[data-view],[data-action],[data-site],[data-work]');if(!el)return;const d=el.dataset;if(d.view){navigate(d.view);document.querySelector('#search-modal').close();}if(d.site){document.querySelector('#search-modal').close();let s=sites.find(s=>s.name===d.site);drawer(s.name,`<div class="drawer-site-icon">${icon(s.icon)}</div><p>${s.location}</p>${badge(s.status,s.status==='Operational'?'success':'warning')}<div class="detail-grid"><div><small>Capacity</small><strong>${s.capacity} MW</strong></div><div><small>Production</small><strong>${s.production} MWh</strong></div><div><small>Availability</small><strong>${s.availability}%</strong></div><div><small>Site manager</small><strong>${s.owner}</strong></div></div><eds-divider></eds-divider><eds-button data-action="new-work">Schedule maintenance</eds-button>`);}if(d.work!==undefined){let w=workOrders[Number(d.work)];drawer(w.title,`<div class="form-stack">${badge(w.priority,w.priority==='High'?'danger':'warning')}<eds-description-list id="work-details"></eds-description-list><eds-alert title="Scheduled" message="The assigned owner will complete this task during the scheduled window." variant="info"></eds-alert></div>`);document.querySelector('#work-details').items=[{term:'Site',description:w.site},{term:'Owner',description:w.owner},{term:'Scheduled',description:w.date},{term:'Notes',description:w.notes||'No additional notes.'}];}
if(d.action==='export')exportReport();if(d.action==='new-work'){document.querySelector('#detail-drawer').close();document.querySelector('#work-modal').show();}if(d.action==='cancel-work')document.querySelector('#work-modal').close();if(d.action==='save-work'){let title=document.querySelector('#work-title').value.trim();let date=document.querySelector('#work-date').value;if(!title||!date){document.querySelector('#form-error').textContent='Enter a task name and scheduled date.';return;}workOrders.unshift({title,site:document.querySelector('#work-site').value,owner:document.querySelector('#work-owner').value,date,priority:document.querySelector('#work-priority').value,notes:document.querySelector('#work-notes').value});window.localStorage.setItem('terra-work-orders',JSON.stringify(workOrders));document.querySelector('#work-modal').close();document.querySelector('#work-title').value='';document.querySelector('#form-error').textContent='';render();toast('Maintenance task scheduled.');}
if(d.action==='notifications'||d.action==='incident'){drawer('Operations activity','<eds-timeline id="activity"></eds-timeline>');document.querySelector('#activity').items=[{title:'Redwood communication loss',description:'Isha Poluru is investigating the PCS connection.',timestamp:'08:15 AM',status:'current'},{title:'Maintenance window started',description:'Neha Poluru · Mesa Valley Solar inverter inspection.',timestamp:'07:30 AM',status:'complete'},{title:'Morning checks completed',description:'Arjun Poluru confirmed Suncrest output is within target.',timestamp:'07:00 AM',status:'complete'}];}
if(d.action==='profile'){drawer('Your workspace',`<div class="form-stack"><eds-avatar name="Aditya Poluru" size="lg"></eds-avatar><h2>Aditya Poluru</h2><p>Operations manager · Terra Energy</p><eds-divider></eds-divider><eds-switch id="compact-toggle" label="Compact layout" ${window.localStorage.getItem('terra-compact')==='true'?'checked':''}></eds-switch><eds-accordion><eds-accordion-item heading="Workspace information"><p>Enterprise · Sample portfolio<br>Timezone: America/Chicago<br>6 energy sites</p></eds-accordion-item></eds-accordion></div>`);document.querySelector('#compact-toggle').addEventListener('eds-change',e=>{const compact=e.target.checked;document.body.classList.toggle('compact',compact);window.localStorage.setItem('terra-compact',compact);});}
if(d.action==='search'){searchResults();document.querySelector('#search-modal').show();}});
document.querySelector('#mega-toggle').addEventListener('click',()=>{const m=document.querySelector('#mega-menu');m.hidden=!m.hidden;document.querySelector('#mega-toggle').setAttribute('aria-expanded',String(!m.hidden));});
document.addEventListener('click',e=>{if(!e.target.closest('#mega-menu,#mega-toggle'))closeMega();});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMega();if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();searchResults();document.querySelector('#search-modal').show();}});
document.querySelector('#global-input').addEventListener('eds-input',e=>searchResults(e.detail.value));document.querySelector('#global-input').addEventListener('eds-change',e=>searchResults(e.detail.value));
document.querySelector('#work-site').options=sites.map(s=>({label:s.name,value:s.name}));document.querySelector('#work-site').value=sites[0].name;
document.querySelector('#work-owner').options=sites.map(s=>({label:s.owner,value:s.owner}));document.querySelector('#work-owner').value=sites[0].owner;
function route(){state.view=nav.find(n=>n.toLowerCase()===location.hash.replace('#/',''))||'Overview';render();}
window.addEventListener('hashchange',route);document.body.classList.toggle('compact',window.localStorage.getItem('terra-compact')==='true');route();
